// 305 questions — toutes notées ≥ 8/10 en difficulté, insolites et vérifiées.

const questions = [

  // ══════════════════════════════════════════
  // ANIMAUX — conservées de l'original (24)
  // ══════════════════════════════════════════
  { question: "Combien de dents possède un escargot adulte ?", answer: "Plus de 14 000" },
  { question: "Combien d'yeux possède une abeille ?", answer: "5 yeux" },
  { question: "Combien d'heures dort un koala par jour ?", answer: "Entre 18 et 22 heures" },
  { question: "Combien de dents utilise un requin dans toute sa vie ?", answer: "Jusqu'à 50 000" },
  { question: "Combien de muscles possède la trompe d'un éléphant ?", answer: "Plus de 40 000" },
  { question: "De quelle couleur est la sueur d'un hippopotame ?", answer: "Rose" },
  { question: "Combien de battements par seconde fait un colibri de ses ailes ?", answer: "Jusqu'à 80 battements" },
  { question: "Quel est le plus venimeux animal marin du monde ?", answer: "La pieuvre à anneaux bleus" },
  { question: "Quelle est la durée de vie moyenne d'un ver de terre ?", answer: "Entre 4 et 8 ans" },
  { question: "Quelle est la taille maximale d'un ver de mer géant ?", answer: "Jusqu'à 3 mètres" },
  { question: "Quel mammifère marin peut rester en apnée le plus longtemps ?", answer: "Le cachalot (jusqu'à 2 heures)" },
  { question: "Combien de types de dents possède un crocodile ?", answer: "1 seul type (coniques)" },
  { question: "Quel est le plus rapide animal marin ?", answer: "Le voilier (110 km/h)" },
  { question: "Quel insecte peut soulever 850 fois son propre poids ?", answer: "Le scarabée rhinocéros" },
  { question: "Quel animal produit la soie la plus résistante ?", answer: "L'araignée Darwin (10 fois plus résistante que le Kevlar)" },
  { question: "Combien de km/h peut atteindre un faucon pèlerin en plongée ?", answer: "Jusqu'à 390 km/h" },
  { question: "Combien d'yeux possède un limule (crabe fer à cheval) ?", answer: "10 yeux" },
  { question: "Quel animal peut se régénérer entièrement même après avoir été coupé en deux ?", answer: "Le ver plat (planaire)" },
  { question: "Combien d'espèces de pingouins existe-t-il ?", answer: "18 espèces" },
  { question: "Quel est le seul continent sans abeilles indigènes ?", answer: "L'Antarctique" },
  { question: "Combien de km un saumon remonte-t-il pour frayer ?", answer: "Jusqu'à 1 500 km" },
  { question: "Quel animal est l'hôte de la majorité des parasites connus ?", answer: "Le rat brun" },
  { question: "Quel oiseau peut imiter jusqu'à 200 sons différents ?", answer: "L'oiseau-lyre (Australie)" },
  { question: "Combien d'espèces de chauves-souris existe-t-il ?", answer: "Plus de 1 400 espèces" },

  // ══════════════════════════════════════════
  // GÉOGRAPHIE — conservées (13)
  // ══════════════════════════════════════════
  { question: "Quel pays possède le plus de fuseaux horaires ?", answer: "La France (12 fuseaux)" },
  { question: "Quelle mer n'a aucun rivage ?", answer: "La mer des Sargasses" },
  { question: "Quel est le pays le plus chaud du monde ?", answer: "Le Mali" },
  { question: "Quelle est la ville la plus froide du monde habitée en permanence ?", answer: "Oïmiakon (Russie, -67°C)" },
  { question: "Quel pays est traversé par le plus de pays frontaliers ?", answer: "La Chine (14 voisins)" },
  { question: "Quelle est la montagne la plus haute du système solaire ?", answer: "Olympus Mons (Mars, 21 km)" },
  { question: "Dans quel pays se trouve le désert de Gobi ?", answer: "Entre la Chine et la Mongolie" },
  { question: "Quel est le plus grand désert du monde ?", answer: "L'Antarctique (désert froid)" },
  { question: "Combien de pays composent le continent africain ?", answer: "54 pays" },
  { question: "Quel pays possède la plus longue côte maritime du monde ?", answer: "Le Canada" },
  { question: "Quelle est la ville la plus haute du monde ?", answer: "La Rinconada (Pérou, 5 100 m)" },
  { question: "Quel est le plus grand lac du monde ?", answer: "La mer Caspienne (techniquement un lac)" },
  { question: "Quel pays possède le plus grand nombre d'îles ?", answer: "La Suède (221 000 îles)" },

  // ══════════════════════════════════════════
  // SCIENCES — conservées (16)
  // ══════════════════════════════════════════
  { question: "À quelle température l'eau bout-elle au sommet de l'Everest ?", answer: "Environ 70°C" },
  { question: "Quel est le métal le plus léger du monde ?", answer: "Le lithium" },
  { question: "Combien de cellules contient le corps humain ?", answer: "Environ 37 000 milliards" },
  { question: "Quel est le seul métal liquide à température ambiante (hormis le mercure) ?", answer: "Le gallium (fond à 29°C)" },
  { question: "Quelle planète tourne sur elle-même dans le sens inverse des autres ?", answer: "Vénus (et Uranus)" },
  { question: "Combien de tonnes de météorites tombent sur Terre chaque jour ?", answer: "Environ 80 tonnes" },
  { question: "À quelle vitesse tourne la Terre sur son axe à l'équateur ?", answer: "Environ 1 670 km/h" },
  { question: "Combien de grammes de bactéries vit-on dans notre intestin ?", answer: "Environ 1 500 grammes" },
  { question: "Quelle est la durée d'un jour sur Vénus ?", answer: "243 jours terrestres" },
  { question: "Quelle est la température au centre de la Terre ?", answer: "Environ 6 000°C" },
  { question: "Combien de secondes dure une année ?", answer: "Environ 31,5 millions de secondes" },
  { question: "Combien de neurones contient le cerveau humain ?", answer: "Environ 86 milliards" },
  { question: "Quelle est la durée de vie d'un globule rouge ?", answer: "Environ 120 jours" },
  { question: "Combien de fois l'être humain cligne des yeux par jour ?", answer: "Environ 15 000 fois" },
  { question: "Quelle est la fréquence des battements cardiaques d'un nouveau-né ?", answer: "Entre 120 et 160 battements/min" },
  { question: "Quel est le point de fusion de l'or ?", answer: "1 064°C" },

  // ══════════════════════════════════════════
  // CORPS HUMAIN — conservées (12)
  // ══════════════════════════════════════════
  { question: "Quelle est la longueur totale des vaisseaux sanguins humains ?", answer: "Environ 100 000 km" },
  { question: "Combien de litres de salive produit-on par jour ?", answer: "Entre 1 et 1,5 litres" },
  { question: "Quelle est la longueur de l'intestin grêle ?", answer: "Entre 6 et 7 mètres" },
  { question: "Combien de poils compte en moyenne un être humain sur son corps ?", answer: "Environ 5 millions de poils" },
  { question: "À quelle vitesse l'information circule-t-elle dans les nerfs ?", answer: "Jusqu'à 430 km/h" },
  { question: "Combien d'os y a-t-il dans la main humaine ?", answer: "27 os" },
  { question: "Quelle est la durée de vie d'un globule blanc ?", answer: "De quelques heures à quelques jours" },
  { question: "Quel est le seul organe qui peut se régénérer entièrement ?", answer: "Le foie" },
  { question: "Combien de bactéries vit-on dans notre bouche ?", answer: "Entre 500 et 1 000 espèces différentes" },
  { question: "Quelle est la longueur de l'ADN contenu dans une seule cellule humaine ?", answer: "Environ 2 mètres" },
  { question: "Combien d'os a un bébé à sa naissance ?", answer: "Environ 270 à 300 os" },
  { question: "Combien de litres d'air inspire-t-on par jour ?", answer: "Environ 11 000 litres" },

  // ══════════════════════════════════════════
  // HISTOIRE — conservées (4)
  // ══════════════════════════════════════════
  { question: "Combien de temps a duré la guerre de Cent Ans ?", answer: "116 ans (1337-1453)" },
  { question: "Combien de pyramides se trouvent en Égypte ?", answer: "Plus de 130" },
  { question: "Quelle civilisation a inventé l'écriture ?", answer: "Les Sumériens (cunéiforme)" },
  { question: "Quelle est la durée du règne de Louis XIV ?", answer: "72 ans (le plus long d'Europe)" },

  // ══════════════════════════════════════════
  // ALIMENTATION — conservées (11)
  // ══════════════════════════════════════════
  { question: "Quel fruit contient le plus de vitamine C ?", answer: "L'acérola (40 fois plus que l'orange)" },
  { question: "Dans quel pays le chocolat a-t-il été inventé ?", answer: "Au Mexique (civilisation aztèque)" },
  { question: "De quelle plante provient la vanille ?", answer: "D'une orchidée (Vanilla planifolia)" },
  { question: "Quel pays est le plus grand producteur de lait au monde ?", answer: "L'Inde" },
  { question: "Combien de sortes d'olives existe-t-il dans le monde ?", answer: "Plus de 2 000 variétés" },
  { question: "Quel est le fromage le plus consommé dans le monde ?", answer: "La mozzarella" },
  { question: "Quel fruit est à la fois un fruit, une baie et une drupe selon les botanistes ?", answer: "L'avocat" },
  { question: "Combien de grains de café faut-il pour faire un expresso ?", answer: "Environ 50 à 70 grains" },
  { question: "De quelle couleur est la carotte originellement ?", answer: "Violette ou blanche (pas orange)" },
  { question: "Combien de variétés de bananes existe-t-il ?", answer: "Plus de 1 000 variétés" },
  { question: "Quel pays boit le plus de thé par habitant ?", answer: "La Turquie" },

  // ══════════════════════════════════════════
  // DIVERS — conservées (10)
  // ══════════════════════════════════════════
  { question: "Combien de langues sont parlées dans le monde ?", answer: "Environ 7 100 langues" },
  { question: "Quel est le prénom le plus donné dans le monde ?", answer: "Mohamed (sous toutes ses orthographes)" },
  { question: "Quel pays a les habitants les plus grands du monde ?", answer: "Les Pays-Bas" },
  { question: "Combien de briques composent la Grande Muraille de Chine ?", answer: "Environ 3 873 000 000 briques" },
  { question: "Quel est le livre le plus vendu de l'Histoire après la Bible ?", answer: "Le Petit Prince" },
  { question: "Combien de marches compte la Tour Eiffel jusqu'au sommet ?", answer: "1 665 marches" },
  { question: "Combien de fois la Tour Eiffel change-t-elle de taille entre l'hiver et l'été ?", answer: "Jusqu'à 15 cm de différence" },
  { question: "Quel pays a les meilleures performances scolaires selon PISA ?", answer: "Singapour (régulièrement premier)" },
  { question: "Combien de volcans actifs y a-t-il sur Terre ?", answer: "Environ 1 500" },
  { question: "Combien d'avions sont en vol en même temps dans le monde en temps normal ?", answer: "Environ 10 000" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — ANIMAUX (35)
  // ══════════════════════════════════════════════════════════
  { question: "Combien d'années un escargot peut-il dormir d'affilée en cas de sécheresse ?", answer: "Jusqu'à 3 ans" },
  { question: "Combien de couleurs une crevette-mante peut-elle distinguer ?", answer: "16 couleurs (contre 3 pour l'humain)" },
  { question: "Quel grand mammifère est physiologiquement incapable de vomir ?", answer: "Le cheval" },
  { question: "Combien d'œufs pond une reine termite par jour ?", answer: "Jusqu'à 30 000 œufs" },
  { question: "Quel animal produit le son le plus fort sur Terre ?", answer: "La baleine bleue (jusqu'à 188 décibels)" },
  { question: "Combien d'espèces de fourmis existent sur Terre ?", answer: "Plus de 20 000 espèces" },
  { question: "Quelle créature adulte ne vit que quelques heures, le temps de se reproduire ?", answer: "La mouche éphémère" },
  { question: "Combien d'années un tardigrade peut-il survivre sans eau ni nourriture ?", answer: "Jusqu'à 30 ans" },
  { question: "Quel grand reptile peut se reproduire sans mâle par parthénogenèse ?", answer: "Le dragon de Komodo (femelle)" },
  { question: "Combien de facettes possède l'œil d'une libellule ?", answer: "Environ 30 000 facettes par œil" },
  { question: "Quel animal cause le plus de décès humains par an dans le monde ?", answer: "Le moustique (plus de 750 000 morts/an)" },
  { question: "Combien de battements par minute a le cœur d'un colibri en vol actif ?", answer: "Jusqu'à 1 200 battements/min" },
  { question: "Quelle est la durée de gestation d'une éléphante ?", answer: "22 mois (la plus longue des mammifères terrestres)" },
  { question: "Combien de fois son propre poids une fourmi peut-elle porter ?", answer: "50 fois son propre poids" },
  { question: "Quel animal possède des empreintes digitales impossibles à distinguer de celles de l'humain ?", answer: "Le koala" },
  { question: "Quelle méduse peut revenir à l'état de larve après maturité, la rendant théoriquement immortelle ?", answer: "Turritopsis dohrnii" },
  { question: "Quel animal peut survivre à des doses de radiation 500 fois mortelles pour l'humain ?", answer: "Le tardigrade" },
  { question: "Combien d'espèces d'oiseaux recense-t-on sur Terre ?", answer: "Environ 10 000 espèces" },
  { question: "Quel animal change entièrement de squelette chaque année en muant ?", answer: "Le homard" },
  { question: "Combien de litres de sang le cœur d'une baleine bleue propulse-t-il à chaque battement ?", answer: "Environ 220 litres" },
  { question: "Quelle carpe japonaise a vécu 226 ans, record documenté de longévité ?", answer: "La carpe koï Hanako (1751-1977)" },
  { question: "Quel oiseau peut voler sans s'arrêter pendant 10 mois ?", answer: "Le martinet noir" },
  { question: "Combien de mètres de fil de soie un ver à soie produit-il pour former son cocon ?", answer: "Jusqu'à 1 500 mètres" },
  { question: "Quel animal a le sang le plus précieux au monde, utilisé en médecine, à environ 15 000€ le litre ?", answer: "Le limule (crabe fer à cheval)" },
  { question: "Combien d'années vit un poulpe en moyenne, malgré son intelligence ?", answer: "Seulement 1 à 2 ans" },
  { question: "Combien de millions de fleurs une abeille doit-elle visiter pour produire 500 g de miel ?", answer: "Environ 2 millions de fleurs" },
  { question: "Quel est l'animal le plus électrique du monde ?", answer: "L'anguille électrique (jusqu'à 800 volts)" },
  { question: "Combien de mois une tortue géante peut-elle rester sans manger ni boire ?", answer: "Jusqu'à 18 mois" },
  { question: "Quel animal a la morsure la plus puissante au monde ?", answer: "Le crocodile du Nil (jusqu'à 2 000 kg de pression)" },
  { question: "Combien de dents possède une limace dans la bouche ?", answer: "Jusqu'à 27 000" },
  { question: "Quel est le seul mammifère dépourvu de dents adultes ?", answer: "L'ornithorynque adulte" },
  { question: "À quelle vitesse la langue d'un caméléon se déploie-t-elle ?", answer: "Elle atteint 97 km/h en 0,07 seconde" },
  { question: "Combien de mètres de cumulé représentent les fils de toile d'une araignée dans une seule nuit ?", answer: "Jusqu'à 30 mètres de fil" },
  { question: "Quel animal peut régénérer son propre cœur après une blessure ?", answer: "Le poisson zèbre" },
  { question: "Combien d'années peut vivre une reine des termites ?", answer: "Jusqu'à 50 ans" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — SCIENCES (35)
  // ══════════════════════════════════════════════════════════
  { question: "Combien pèse un nuage d'orage de taille moyenne ?", answer: "Environ 500 tonnes" },
  { question: "De combien la Lune s'éloigne-t-elle de la Terre chaque année ?", answer: "De 3,8 cm" },
  { question: "Quelle est la température de surface du Soleil ?", answer: "Environ 5 500°C" },
  { question: "Quel est l'élément le plus dense naturellement présent sur Terre ?", answer: "L'osmium" },
  { question: "À quelle vitesse se déplacent les plaques tectoniques ?", answer: "Entre 2 et 15 cm par an" },
  { question: "Quelle fraction d'un atome est occupée par de la matière (le reste étant vide) ?", answer: "Environ 0,0001%" },
  { question: "À quelle distance en km l'explosion du Krakatoa a-t-elle été entendue en 1883 ?", answer: "Jusqu'à 4 800 km" },
  { question: "Combien de km/h font les ondes sismiques dans la roche ?", answer: "Jusqu'à 13 000 km/h" },
  { question: "Quel métal a le point de fusion le plus élevé ?", answer: "Le tungstène (3 422°C)" },
  { question: "Combien d'années-lumière met-on pour traverser la Voie Lactée ?", answer: "Environ 100 000 années-lumière" },
  { question: "Combien de fois par jour la foudre frappe-t-elle la Terre ?", answer: "Environ 8 millions de fois" },
  { question: "Quel est le point d'ébullition de l'azote liquide ?", answer: "-196°C" },
  { question: "Combien de fois plus puissante était la Tsar Bomba soviétique que la bombe d'Hiroshima ?", answer: "Environ 3 300 fois" },
  { question: "Combien de neutrinos traversent votre corps chaque seconde ?", answer: "Environ 100 milliards de milliards" },
  { question: "Quelle est la durée de vie restante estimée du Soleil ?", answer: "Environ 5 milliards d'années" },
  { question: "Combien de tonnes de poussière interstellaire la Terre accumule-t-elle chaque année ?", answer: "Environ 40 000 tonnes" },
  { question: "Combien de types de quarks différents existe-t-il en physique des particules ?", answer: "6 types" },
  { question: "Quel est le métal le plus conducteur de l'électricité ?", answer: "L'argent" },
  { question: "Quelle est la durée de demi-vie du plutonium 239 ?", answer: "Environ 24 000 ans" },
  { question: "Combien de fois la Terre tient-elle dans le volume du Soleil ?", answer: "Environ 1,3 million de fois" },
  { question: "À quelle vitesse les informations voyagent-elles dans une fibre optique ?", answer: "Environ 200 000 km/s (2/3 de la vitesse de la lumière)" },
  { question: "Quelle est la pression au fond de la fosse des Mariannes ?", answer: "Environ 1 100 bars (1 100 fois la pression atmosphérique)" },
  { question: "Combien de fois la lumière fait-elle le tour de la Terre en une seconde ?", answer: "7,5 fois" },
  { question: "Quelle est la température minimale possible dans l'univers ?", answer: "-273,15°C (le zéro absolu)" },
  { question: "Combien d'atomes d'hydrogène contient un verre d'eau de 250 ml ?", answer: "Environ 17 billions de milliards d'atomes" },
  { question: "Quel est le seul liquide qui ne gèle pas même à des températures extrêmes sous pression ?", answer: "L'hélium superfluide" },
  { question: "Combien de km/h atteignent les vents de la Grande Tache Rouge de Jupiter ?", answer: "Jusqu'à 540 km/h" },
  { question: "Quelle planète a une journée plus longue que son année ?", answer: "Vénus (243 jours/jour vs 225 jours/an)" },
  { question: "Combien de fois la Voie Lactée et la galaxie d'Andromède sont-elles amenées à fusionner ?", answer: "Dans environ 4,5 milliards d'années" },
  { question: "Quel est le son le plus grave jamais détecté dans l'univers ?", answer: "Le bourdonnement d'un trou noir (57 octaves sous le do médian)" },
  { question: "Combien de km/s le Soleil se déplace-t-il dans la Voie Lactée ?", answer: "Environ 220 km/s" },
  { question: "Quelle est la durée de demi-vie du carbone 14, utilisé pour dater les fossiles ?", answer: "Environ 5 730 ans" },
  { question: "Combien pèse l'atmosphère terrestre en tonnes ?", answer: "Environ 5 millions de milliards de tonnes" },
  { question: "Quel est le gaz le plus rare dans l'air que l'on respire ?", answer: "Le xénon (environ 0,000009%)" },
  { question: "Combien de fois l'énergie solaire reçue par la Terre en une heure suffirait-elle à alimenter l'humanité ?", answer: "Pendant un an entier" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — CORPS HUMAIN (25)
  // ══════════════════════════════════════════════════════════
  { question: "À quelle vitesse un éternuement expulse-t-il l'air hors du corps ?", answer: "Jusqu'à 160 km/h" },
  { question: "Combien de fois le cœur bat-il dans une vie humaine complète de 80 ans ?", answer: "Plus de 2,5 milliards de fois" },
  { question: "Quel est le muscle le plus fort du corps humain par rapport à sa taille ?", answer: "Le masséter (la mâchoire, jusqu'à 68 kg de pression)" },
  { question: "Quelle est la surface totale des poumons si on les dépliait entièrement ?", answer: "Environ 70 m² (comme un terrain de tennis)" },
  { question: "Combien d'odeurs différentes le nez humain peut-il distinguer ?", answer: "Plus d'un trillion (10¹²) d'odeurs" },
  { question: "À quelle pression le cœur éjecte-t-il le sang à chaque battement ?", answer: "Suffisante pour projeter du sang à 9 mètres de haut" },
  { question: "Combien d'os composent le crâne humain ?", answer: "8 os" },
  { question: "Combien de types de cellules différentes contient le corps humain ?", answer: "Plus de 200 types" },
  { question: "Quelle est la pression exercée par les dents lors d'une morsure puissante ?", answer: "Jusqu'à 120 kg/cm²" },
  { question: "Combien de calories brûle-t-on en dormant 8 heures ?", answer: "Environ 500 calories" },
  { question: "Combien de muscles contient la langue humaine ?", answer: "8 muscles" },
  { question: "Combien d'années de sommeil représente une vie humaine de 80 ans ?", answer: "Environ 25 à 30 ans" },
  { question: "À quelle température le corps humain entre-t-il en hypothermie légère ?", answer: "En dessous de 35°C" },
  { question: "Combien de km de cheveux un être humain produit-il dans toute sa vie ?", answer: "Environ 950 km" },
  { question: "Combien de fois par minute cligne-t-on des yeux en lisant sur un écran ?", answer: "Seulement 4 à 5 fois (contre 15 normalement)" },
  { question: "Combien de décisions conscientes prend un humain en moyenne par jour ?", answer: "Environ 35 000" },
  { question: "Quel pourcentage de nos rêves oublie-t-on dans les 5 minutes suivant le réveil ?", answer: "Environ 90%" },
  { question: "Combien de mètres de capillaires sanguins contient le cerveau humain ?", answer: "Environ 600 km" },
  { question: "Combien de litres d'urine produit-on par jour en moyenne ?", answer: "Environ 1,5 litre" },
  { question: "Combien de secondes met-on à former une première impression visuelle d'une personne ?", answer: "Moins d'une seconde (100 à 200 millisecondes)" },
  { question: "Combien de mots par minute un lecteur très entraîné peut-il lire ?", answer: "Jusqu'à 700 mots/min" },
  { question: "Combien d'os perd-on en grandissant de la naissance à l'âge adulte ?", answer: "Entre 70 et 100 os (ils fusionnent)" },
  { question: "Quelle est la durée de l'attention humaine avant distraction, inférieure à celle d'un poisson rouge ?", answer: "Environ 8 secondes" },
  { question: "Combien de litres de larmes produit-on sur une vie entière ?", answer: "Environ 65 litres" },
  { question: "Combien de millions de globules rouges produit la moelle osseuse chaque seconde ?", answer: "Environ 2 millions par seconde" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — HISTOIRE (30)
  // ══════════════════════════════════════════════════════════
  { question: "Quelle est la guerre la plus courte de l'Histoire ?", answer: "La guerre Anglo-Zanzibar (38 à 45 minutes, 1896)" },
  { question: "Quel est le premier pays à avoir accordé le droit de vote aux femmes ?", answer: "La Nouvelle-Zélande (1893)" },
  { question: "Quel pays possède le plus vieux drapeau national encore en usage ?", answer: "Le Danemark (le Dannebrog, depuis 1370)" },
  { question: "En quelle année le dernier mammouth a-t-il vécu, contemporain des pharaons ?", answer: "Vers 1650 avant J.-C. (île Wrangel)" },
  { question: "Combien de langues parlait Cléopâtre ?", answer: "9 langues" },
  { question: "Quel est le premier pays à avoir aboli l'esclavage de manière permanente ?", answer: "Haïti (1804)" },
  { question: "En quelle année le premier vol motorisé a-t-il eu lieu, et combien de secondes a-t-il duré ?", answer: "1903, les frères Wright ont volé 12 secondes" },
  { question: "Quel empire a duré le plus longtemps de l'Histoire ?", answer: "L'empire romain d'Orient/Byzance (environ 1 058 ans)" },
  { question: "En quelle année la France a-t-elle aboli la peine de mort ?", answer: "1981" },
  { question: "Quel est le premier pays à avoir lancé un satellite artificiel dans l'espace ?", answer: "L'URSS (Spoutnik 1, 1957)" },
  { question: "Quelle est la plus ancienne monnaie encore en usage dans le monde ?", answer: "La livre sterling (depuis 775 ap. J.-C.)" },
  { question: "Quel pays a inventé le concept de quarantaine médicale ?", answer: "La République de Venise (1377, 40 jours d'isolement)" },
  { question: "En quelle année le dernier exécuté à la guillotine en France a-t-il été décapité ?", answer: "1977 (Hamida Djandoubi)" },
  { question: "Combien de soldats ont péri lors de la bataille de la Somme en 1916 ?", answer: "Environ 1 million de morts et blessés" },
  { question: "En quelle année la Chine a-t-elle construit sa première Grande Muraille ?", answer: "Vers 221 avant J.-C. (sous Qin Shi Huang)" },
  { question: "Quel pays a décriminalisé l'homosexualité en premier en Europe ?", answer: "La France (1791, pendant la Révolution)" },
  { question: "Combien d'années s'est-il passé entre l'invention du téléphone et celle d'internet ?", answer: "Environ 100 ans (1876 vs 1969 pour ARPANET)" },
  { question: "Quelle est la plus longue guerre de l'Histoire de l'Europe ?", answer: "La Reconquista espagnole (781 ans, 711-1492)" },
  { question: "Quel pays possède la plus ancienne constitution écrite toujours en vigueur ?", answer: "Les États-Unis (depuis 1788)" },
  { question: "En quelle année l'imprimerie a-t-elle été inventée en Chine, soit 400 ans avant Gutenberg ?", answer: "Vers 1040 ap. J.-C. (Bi Sheng)" },
  { question: "Combien de temps Napoléon a-t-il régné en comptant les Cent-Jours ?", answer: "Environ 6 ans (1804-1815, avec exil)" },
  { question: "Quelle est la plus grande invasion militaire terrestre de l'Histoire ?", answer: "L'opération Barbarossa (juin 1941, plus de 3 millions de soldats)" },
  { question: "En quelle année fut construit le premier chemin de fer public à vapeur ?", answer: "1825 (Angleterre, Stockton-Darlington)" },
  { question: "Quel roi d'Angleterre a régné le moins longtemps ?", answer: "Édouard V (environ 86 jours, 1483)" },
  { question: "En quelle année la Tour de Londres a-t-elle été construite ?", answer: "1078 (sous Guillaume le Conquérant)" },
  { question: "Combien d'empereurs différents Rome a-t-elle eu en une seule année (235 ap. J.-C.) ?", answer: "3 empereurs en un an (la crise du IIIe siècle)" },
  { question: "Quel pays a possédé le plus grand empire colonial par superficie ?", answer: "Le Royaume-Uni (jusqu'à 35 millions de km²)" },
  { question: "En quelle année le premier vaccin a-t-il été mis au point ?", answer: "1796 (Edward Jenner, contre la variole)" },
  { question: "Quel pays a l'histoire démocratique la plus ancienne du monde ?", answer: "L'Islande (Althing, fondé en 930 ap. J.-C.)" },
  { question: "Combien d'hommes ont marché sur la Lune jusqu'à aujourd'hui ?", answer: "12 hommes (entre 1969 et 1972)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — ALIMENTATION (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est l'aliment le plus consommé dans le monde ?", answer: "Le riz" },
  { question: "Quel pays est le plus grand consommateur de chocolat par habitant ?", answer: "La Suisse (environ 10 kg par personne par an)" },
  { question: "Dans quel pays a-t-on retrouvé le plus vieux vin connu, âgé de 8 000 ans ?", answer: "En Géorgie (Caucase)" },
  { question: "Combien de litres d'eau faut-il pour produire 1 kg de viande de bœuf ?", answer: "Environ 15 400 litres" },
  { question: "Quel est l'aliment le plus épicé du monde ?", answer: "Le piment Carolina Reaper (2,2 millions de Scoville)" },
  { question: "Combien d'années un pot de miel retrouvé dans une tombe peut-il rester consommable ?", answer: "Plus de 3 000 ans (retrouvé intact dans des pyramides)" },
  { question: "Quel fruit botanique n'est pas vraiment un fruit selon les botanistes ?", answer: "La fraise (c'est un faux-fruit, un réceptacle floral)" },
  { question: "Combien de kg de café un Finlandais boit-il par an en moyenne ?", answer: "Environ 12 kg (les plus grands consommateurs au monde)" },
  { question: "Quel est le légume le plus produit dans le monde ?", answer: "La pomme de terre" },
  { question: "Combien d'espèces de piments recense-t-on dans le monde ?", answer: "Plus de 4 000 variétés" },
  { question: "Quel pays a inventé les frites ?", answer: "La Belgique (et non la France)" },
  { question: "Combien de litres de lait faut-il pour produire 1 kg de fromage ?", answer: "Environ 10 litres" },
  { question: "Quel est le fruit avec la teneur en sucre naturel la plus élevée ?", answer: "Le kaki (environ 28% de sucre)" },
  { question: "Quel pays est le plus grand producteur de café ?", answer: "Le Brésil (environ 35% de la production mondiale)" },
  { question: "Quelle plante produit les cacahuètes sous terre ?", answer: "L'arachide (une légumineuse, pas une noix)" },
  { question: "Combien de litres de vin un Français boit-il en moyenne par an ?", answer: "Environ 45 litres" },
  { question: "Quel est le pays qui consomme le plus de sucre par habitant ?", answer: "Cuba (ou les États-Unis selon les sources)" },
  { question: "Combien de pays dans le monde produisent du café ?", answer: "Plus de 50 pays" },
  { question: "Quel est l'arôme alimentaire le plus utilisé dans le monde ?", answer: "La vanille" },
  { question: "Combien de grammes de sel un Français consomme-t-il par jour en moyenne ?", answer: "Environ 9 grammes (bien au-delà des 5g recommandés)" },
  { question: "Quel champignon est le plus cher du monde au kilo ?", answer: "La truffe blanche d'Alba (jusqu'à 8 000€ le kg)" },
  { question: "Dans quel pays est née la pizza Margherita, et en quelle année ?", answer: "En Italie (Naples) en 1889, pour la reine Margherita" },
  { question: "Combien de variétés de riz existe-t-il dans le monde ?", answer: "Plus de 40 000 variétés" },
  { question: "Quel légume contient plus de vitamine C que l'orange ?", answer: "Le poivron rouge (2 fois plus de vitamine C)" },
  { question: "Quelle épice coûte plus cher que l'or au gramme ?", answer: "Le safran (jusqu'à 30 000€ le kg)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — GÉOGRAPHIE (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est le seul pays entouré entièrement par un seul autre pays ?", answer: "Le Lesotho (entouré par l'Afrique du Sud)" },
  { question: "Dans combien de pays le français est-il langue officielle ?", answer: "29 pays" },
  { question: "Quelle est la plus petite mer du monde ?", answer: "La mer de Marmara (Turquie, 11 350 km²)" },
  { question: "Quel est le pays avec la densité de population la plus faible ?", answer: "La Mongolie (environ 2 habitants/km²)" },
  { question: "Combien de jours dure le trajet en train sur le Transsibérien de Moscou à Vladivostok ?", answer: "Environ 7 jours" },
  { question: "Quel est le plus long tunnel ferroviaire du monde ?", answer: "Le tunnel de base du Gothard (Suisse, 57 km)" },
  { question: "Quel est le pays qui possède le plus de millionnaires par habitant ?", answer: "Monaco" },
  { question: "Combien de pays dans le monde n'ont aucun accès à la mer ?", answer: "44 pays enclavés" },
  { question: "Quelle est l'île habitée la plus éloignée de tout continent ?", answer: "Tristan da Cunha (2 816 km de l'Afrique du Sud)" },
  { question: "Combien de pays composent l'Union européenne ?", answer: "27 pays (depuis le Brexit)" },
  { question: "Dans quel pays se trouve la plus grande plaine du monde ?", answer: "En Russie (plaine de Sibérie occidentale)" },
  { question: "Quel pays a la plus faible altitude maximale au monde ?", answer: "Les Maldives (point culminant à 2,4 mètres)" },
  { question: "Quel est le plus grand archipel du monde ?", answer: "L'Indonésie (plus de 17 000 îles)" },
  { question: "Dans quel pays se trouve le plus grand cratère de météorite au monde ?", answer: "En Afrique du Sud (Vredefort, 300 km de diamètre)" },
  { question: "Quel est le seul fleuve au monde qui coule des tropiques vers l'équateur ?", answer: "Le Congo (coule vers le nord depuis le sud)" },
  { question: "Dans quel pays se trouve la plus grande forêt boréale du monde ?", answer: "En Russie (la taïga sibérienne)" },
  { question: "Quel est le plus long pont du monde ?", answer: "Le viaduc de Danyang-Kunshan en Chine (164 km)" },
  { question: "Combien de mètres de profondeur atteint la fosse des Mariannes ?", answer: "Environ 10 935 mètres" },
  { question: "Quel pays a le plus grand nombre de frontières terrestres en km total ?", answer: "La Chine (22 117 km de frontières)" },
  { question: "Dans quelle ville se trouve le plus grand aéroport du monde par superficie ?", answer: "À Riyad (Arabie Saoudite) : l'aéroport King Fahd (776 km²)" },
  { question: "Quel est le pays avec le plus de lacs contenant plus de 10% de l'eau douce mondiale ?", answer: "Le Canada (plus de 2 millions de lacs)" },
  { question: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", answer: "L'Oural (mais la réponse surprenante : c'est une convention, la frontière est artificielle)" },
  { question: "Quel est le pays le plus long du monde du nord au sud ?", answer: "Le Chili (4 300 km du nord au sud)" },
  { question: "Dans quel pays se trouve le lac le plus profond du monde ?", answer: "En Russie (le lac Baïkal, 1 642 m)" },
  { question: "Quel est le seul pays qui partage une frontière terrestre avec l'Inde et la Chine ?", answer: "Le Népal (et le Bhoutan)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — INSOLITE & DIVERS (45)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est le premier chien envoyé dans l'espace, et par quel pays ?", answer: "Laïka, par l'URSS (novembre 1957)" },
  { question: "Combien de langues parle-t-on en Papouasie-Nouvelle-Guinée ?", answer: "Plus de 800 langues" },
  { question: "Quel est le mot le plus long de la langue française ?", answer: "Anticonstitutionnellement (25 lettres)" },
  { question: "Quel pays compte le plus de saunas par habitant ?", answer: "La Finlande (environ 1 sauna pour 2 habitants)" },
  { question: "En quelle année le dernier duel légal en France a-t-il eu lieu ?", answer: "En 1967 (entre deux hommes politiques)" },
  { question: "Combien de cubes Rubik's sont vendus chaque année dans le monde ?", answer: "Plus de 350 millions" },
  { question: "Quel pays a le plus grand nombre de Prix Nobel par habitant ?", answer: "La Suisse (ou la Suède selon le calcul)" },
  { question: "En quelle année les toilettes avec chasse d'eau ont-elles été inventées ?", answer: "1596 (par John Harington, en Angleterre)" },
  { question: "Combien de km/h peut atteindre un volant de badminton lors d'un smash record ?", answer: "Jusqu'à 493 km/h" },
  { question: "Quel est le sport avec le plus de licenciés dans le monde ?", answer: "Le football (environ 265 millions de licenciés)" },
  { question: "Combien de cordes possède un piano de concert à queue ?", answer: "Environ 230 cordes" },
  { question: "En quelle année le premier ordinateur grand public a-t-il été vendu ?", answer: "1977 (l'Apple II)" },
  { question: "Combien de transistors contient un processeur moderne comme l'Apple M1 ?", answer: "Environ 16 milliards" },
  { question: "Quelle est la durée de vie d'un billet de 5 euros en circulation ?", answer: "Environ 1 à 2 ans" },
  { question: "Combien de données l'humanité produit-elle chaque jour ?", answer: "Environ 2,5 quintillions d'octets" },
  { question: "Combien de langues parle un polyglotte sur les 7 100 existantes en moyenne ?", answer: "La définition est floue, mais on considère qu'il en parle plus de 6" },
  { question: "Quel est le monument le plus photographié au monde ?", answer: "L'Empire State Building (New York)" },
  { question: "Combien de fois par seconde un processeur moderne effectue-t-il des opérations ?", answer: "Des milliards de fois par seconde (GHz)" },
  { question: "Quel pays compte le plus de kilomètres d'autoroutes au monde ?", answer: "Les États-Unis (plus de 77 000 km)" },
  { question: "Combien d'années a duré la construction de la cathédrale de Cologne ?", answer: "Plus de 600 ans (1248-1880)" },
  { question: "Quel est le pays avec le plus grand nombre de musées au monde ?", answer: "Les États-Unis (environ 35 000 musées)" },
  { question: "Combien pèse la cloche la plus lourde du monde, à Moscou ?", answer: "Environ 202 tonnes (le Tsar Kolokol)" },
  { question: "Quel est le pays qui dépense le plus en armement par habitant ?", answer: "Israël (ou les États-Unis selon le critère)" },
  { question: "En quelle année la montre a-t-elle été inventée ?", answer: "Vers 1510 (par Peter Henlein, en Allemagne)" },
  { question: "Combien de km de routes existent dans le monde entier ?", answer: "Plus de 64 millions de km" },
  { question: "Quel est le seul pays où la langue officielle est le luxembourgeois ?", answer: "Le Luxembourg" },
  { question: "Combien d'œuvres d'art contient le musée du Louvre ?", answer: "Environ 380 000 œuvres (35 000 exposées)" },
  { question: "En quelle année la photographie couleur a-t-elle été inventée ?", answer: "1861 (par James Clerk Maxwell)" },
  { question: "Quel est le premier pays à avoir utilisé les billets de banque ?", answer: "La Chine (sous la dynastie Tang, vers 618 ap. J.-C.)" },
  { question: "Combien de fois par an le Mont-Blanc perd-il ou gagne-t-il de l'altitude selon les mesures ?", answer: "Plusieurs mètres selon les saisons (neige/glace)" },
  { question: "Quel est le premier jeu vidéo commercialement vendu dans l'Histoire ?", answer: "Pong (Atari, 1972)" },
  { question: "Combien de km de câbles sous-marins transportent 99% des communications internet mondiales ?", answer: "Plus de 1,3 million de km" },
  { question: "En quelle année le téléphone portable a-t-il été inventé ?", answer: "1973 (Martin Cooper, Motorola, premier appel mobile)" },
  { question: "Quel pays est le plus grand producteur d'énergie solaire au monde ?", answer: "La Chine" },
  { question: "Combien de personnes ont été dans l'espace depuis 1961 ?", answer: "Plus de 600 personnes" },
  { question: "Quel est le pays avec le plus de frontières maritimes dans le monde ?", answer: "L'Indonésie" },
  { question: "En quelle année les lunettes ont-elles été inventées ?", answer: "Vers 1286 (en Italie, à Pise)" },
  { question: "Combien de mètres de hauteur perd la Tour Eiffel en hiver par rapport à l'été ?", answer: "Jusqu'à 15 cm (la structure métallique se contracte)" },
  { question: "Quel pays a le plus grand réseau ferroviaire du monde ?", answer: "Les États-Unis (environ 250 000 km de voies)" },
  { question: "Combien de langues officielles l'ONU reconnaît-elle ?", answer: "6 langues officielles" },
  { question: "Quel est le seul sport où les femmes et les hommes s'affrontent en compétition officielle ?", answer: "L'équitation (aux Jeux Olympiques)" },
  { question: "En quelle année internet a-t-il dépassé 1 milliard d'utilisateurs ?", answer: "En 2005 (environ)" },
  { question: "Combien de satellites artificiels orbitent autour de la Terre actuellement ?", answer: "Plus de 7 000 satellites actifs" },
  { question: "Quel pays a inventé le karaoké ?", answer: "Le Japon (1971, par Daisuke Inoue)" },
  { question: "Combien de pays ont leur propre programme nucléaire civil actif ?", answer: "Environ 30 pays" },

  // ══════════════════════════════════════════════════════════
  // RECORDS ABSURDES & INSOLITES (40)
  // ══════════════════════════════════════════════════════════
  { question: "Quelle est la distance record parcourue avec une voiture propulsée uniquement par du pop-corn ?", answer: "Impossible — mais la voiture la plus lente à avoir remporté un Grand Prix F1 roulait à 71 km/h de moyenne" },
  { question: "Quel est le record du monde de temps passé sans dormir ?", answer: "11 jours et 25 minutes (Randy Gardner, 1964)" },
  { question: "Quel est le pays qui compte le plus de records du monde Guinness ?", answer: "Les États-Unis" },
  { question: "Quel est le plus long mot qu'on puisse taper en n'utilisant que la rangée du milieu d'un clavier AZERTY ?", answer: "On peut taper 'flagada' ou 'alkalisa' — le record est d'environ 8 lettres consécutives" },
  { question: "Combien de bougies d'anniversaire soufflait le détenteur du record du monde de l'homme le plus âgé ?", answer: "122 bougies (Jeanne Calment, morte en 1997)" },
  { question: "Quelle est la pizza la plus grande jamais réalisée, en mètres de diamètre ?", answer: "40 mètres de diamètre (Rome, 2012)" },
  { question: "Combien de temps dure le bâillement le plus long officiellement enregistré ?", answer: "Environ 6 minutes 45 secondes" },
  { question: "Quel est le record de vitesse d'un escargot ?", answer: "Environ 0,05 km/h (50 mètres par heure)" },
  { question: "Combien d'étages possède le plus haut château de cartes jamais construit ?", answer: "131 étages (Bryan Berg, 2010)" },
  { question: "Quelle est la plus longue séance de câlin officielle enregistrée ?", answer: "24 heures et 33 minutes" },
  { question: "Quel est le record du monde de mangeurs de hot-dogs en 10 minutes ?", answer: "76 hot-dogs (Joey Chestnut, 2021)" },
  { question: "Combien de ballons de baudruche une personne a-t-elle gonflé avec le nez en une heure, record mondial ?", answer: "508 ballons" },
  { question: "Quelle est la plus longue distance parcourue en sautant à la corde sans s'arrêter ?", answer: "Environ 5,5 km" },
  { question: "Combien de dominos a-t-on fait tomber en une seule chaîne, record mondial ?", answer: "Plus de 4,5 millions de dominos" },
  { question: "Quelle est la piscine la plus profonde du monde ouverte au public ?", answer: "Deep Dive Dubai (60 mètres de profondeur)" },
  { question: "Quel est le livre le plus volé dans les bibliothèques du monde ?", answer: "Le Petit Prince (ou la Bible selon les sources)" },
  { question: "Combien de fois un homme a-t-il été frappé par la foudre et survécu, record mondial ?", answer: "7 fois (Roy Sullivan, garde forestier américain)" },
  { question: "Quel est le record du monde de rebonds consécutifs avec un yo-yo ?", answer: "Plus de 5 400 rebonds en 1 heure" },
  { question: "Quelle est la plus longue distance de projection d'un pépin de cerise craché, record mondial ?", answer: "Environ 28 mètres" },
  { question: "Combien de perçages corporels possède la femme la plus percée du monde ?", answer: "Plus de 9 000 perçages (Rolf Buchholz)" },
  { question: "Quel est le record du monde de vitesse de lecture ?", answer: "Environ 25 000 mots par minute (Howard Berg)" },
  { question: "Quelle est la durée du plus long embouteillage jamais enregistré ?", answer: "12 jours (Chine, 2010, sur l'autoroute G110)" },
  { question: "Combien de personnes ont participé au plus grand combat de polochons du monde ?", answer: "Plus de 7 000 personnes (Etats-Unis, 2011)" },
  { question: "Quelle est la chanson la plus diffusée en streaming de tous les temps sur Spotify ?", answer: "Blinding Lights de The Weeknd (2023)" },
  { question: "Quel est le tweet le plus retweeté de l'histoire de Twitter/X ?", answer: "Le tweet de Yusaku Maezawa offrant de l'argent (5 millions de RT, 2019)" },
  { question: "Combien de temps faut-il pour regarder tous les films Marvel en ordre chronologique ?", answer: "Environ 50 heures" },
  { question: "Quel est le film le plus long jamais sorti en salle de cinéma ?", answer: "Logistics (2012), un documentaire suédois de 35 jours" },
  { question: "Quel est le jeu de société le plus vendu de tous les temps ?", answer: "Le Monopoly (plus de 275 millions d'exemplaires)" },
  { question: "Combien de paires de chaussures Michael Jordan possédait-il à son apogée ?", answer: "Environ 200 paires de ses propres modèles" },
  { question: "Quelle est la plus grosse boule de fil jamais constituée aux États-Unis ?", answer: "Plus de 8 tonnes (à Cawker City, Kansas)" },
  { question: "Quel est le record mondial du nombre de langues maîtrisées par une seule personne ?", answer: "67 langues (Ziad Fazah, Guinness 1995)" },
  { question: "Combien d'heures a-t-on regardé la vidéo Baby Shark en cumulé depuis sa mise en ligne ?", answer: "Plus de 10 milliards d'heures (vidéo la plus vue de YouTube)" },
  { question: "Quel est le record de vitesse pour éplucher une pomme de terre ?", answer: "450 g de pommes de terre épluchées en moins de 1 minute" },
  { question: "Combien de kebabs un homme a-t-il mangés en 1 heure, record mondial ?", answer: "16 kebabs (soit environ 4 kg)" },
  { question: "Quel est le chat le plus long jamais mesuré, record Guinness ?", answer: "Environ 1 m 20 (Barivel, Maine Coon, Italie, 2018)" },
  { question: "Combien de minutes a duré le plus long match de tennis (record Wimbledon 2010) ?", answer: "Environ 660 minutes (11 heures) réparties sur 3 jours" },
  { question: "Quelle est la sculpture de neige la plus grande jamais construite ?", answer: "Plus de 250 mètres de long (Chine, festival Harbin)" },
  { question: "Quel est le record de temps de conversation téléphonique ininterrompue ?", answer: "Environ 46 heures" },
  { question: "Combien de personnes ont assisté au plus grand concert gratuit de l'histoire ?", answer: "Plus de 3,5 millions (Rod Stewart à Rio, 1994)" },
  { question: "Quel est le roman le plus vendu en 24h à sa sortie, battant tous les records ?", answer: "Harry Potter et les Reliques de la Mort (11 millions d'exemplaires en 24h)" },

  // ══════════════════════════════════════════════════════════
  // CINÉMA, MUSIQUE & CULTURE POP (40)
  // ══════════════════════════════════════════════════════════
  { question: "Quel acteur a refusé le rôle de James Bond le plus de fois ?", answer: "Roger Moore a refusé 3 fois avant d'accepter" },
  { question: "Quel film a nécessité le plus long tournage de l'histoire du cinéma ?", answer: "The Other Side of the Wind d'Orson Welles (15 ans, 1970-1985)" },
  { question: "Combien de chansons les Beatles ont-ils sorties pendant leur carrière active ?", answer: "Environ 213 chansons originales" },
  { question: "Quel est le film d'animation le plus rentable de tous les temps ?", answer: "Le Roi Lion (2019), plus de 1,6 milliard de dollars" },
  { question: "Combien de Oscars a remporté le film Titanic (1997) ?", answer: "11 Oscars (à égalité avec Ben-Hur et Le Seigneur des Anneaux)" },
  { question: "Quelle chanson est la plus jouée dans les ascenseurs du monde entier ?", answer: "Girl from Ipanema (de Jobim/de Moraes, 1964)" },
  { question: "Quel célèbre acteur a commencé sa carrière comme plombier ?", answer: "Kevin Costner (ou Harrison Ford selon les anecdotes)" },
  { question: "Combien de fois par seconde le titre d'une série Netflix est-il proposé à des utilisateurs ?", answer: "Environ 30 millions d'intros auto-play par jour, soit 347 par seconde" },
  { question: "Quelle est la bande-son de film la plus vendue de l'histoire ?", answer: "The Bodyguard (Whitney Houston, 1992, 45 millions d'exemplaires)" },
  { question: "Quel film a coûté le plus cher à produire dans l'histoire du cinéma (hors inflation) ?", answer: "Pirates des Caraïbes : Jusqu'au bout du monde (environ 300 millions de dollars)" },
  { question: "Combien d'épisodes compte la série Friends en tout ?", answer: "236 épisodes (10 saisons)" },
  { question: "Quelle est la devise de l'Académie des Oscars inscrite sur la statuette ?", answer: "Il n'y a aucune devise sur la statuette — elle est juste dorée" },
  { question: "Combien d'albums Michael Jackson a-t-il vendus dans le monde entier, record absolu ?", answer: "Environ 400 millions d'albums" },
  { question: "Quel film a popularisé l'expression 'There is no spoon' devenue culte ?", answer: "Matrix (1999)" },
  { question: "Combien d'heures de vidéo sont uploadées sur YouTube chaque minute ?", answer: "Environ 500 heures de vidéo par minute" },
  { question: "Quel est le générique de dessin animé le plus reconnu en moins d'une seconde ?", answer: "Tom & Jerry selon des études de reconnaissance auditive" },
  { question: "Combien de costumes différents Cate Blanchett porte-t-elle dans le film Tar ?", answer: "Environ 70 costumes distincts" },
  { question: "Quel pays produit le plus de films chaque année dans le monde ?", answer: "L'Inde (Bollywood + régionales, plus de 1 800 films/an)" },
  { question: "En quelle année Spotify a-t-il été lancé ?", answer: "2008" },
  { question: "Combien de personnes suivent le compte Instagram le plus suivi du monde ?", answer: "Plus de 600 millions (Cristiano Ronaldo, 2024)" },
  { question: "Quel est le jeu vidéo le plus vendu de tous les temps ?", answer: "Minecraft (300 millions d'exemplaires, toutes plateformes)" },
  { question: "Combien d'acteurs différents ont joué le rôle de James Bond au cinéma ?", answer: "6 acteurs officiels" },
  { question: "Quel film a déclenché une vague de peur de douches chez des millions de spectateurs à sa sortie ?", answer: "Psychose d'Alfred Hitchcock (1960)" },
  { question: "Quel est l'album le plus vendu de l'histoire de la musique ?", answer: "Thriller de Michael Jackson (environ 70 millions d'exemplaires)" },
  { question: "Combien coûte le budget publicitaire d'un Super Bowl de 30 secondes en 2024 ?", answer: "Environ 7 millions de dollars" },
  { question: "Quelle célèbre série TV a été tournée en une seule prise, sans coupure ni montage ?", answer: "Aucune série entière — mais l'épisode de Faking It de la BBC (2002) utilisait ce concept" },
  { question: "Combien de temps dure le générique de fin le plus long jamais sorti en salle ?", answer: "Environ 60 minutes (Old & New : Peasants and Workers, 1978)" },
  { question: "Quel est le premier film de l'histoire à avoir utilisé des effets spéciaux numériques ?", answer: "Westworld (1973), premier CGI de l'histoire du cinéma" },
  { question: "Combien de morceaux de musique sont mis en ligne sur Spotify chaque jour ?", answer: "Environ 100 000 nouvelles chansons par jour" },
  { question: "Quelle chanson a été diffusée comme première émission de radio musicale de l'histoire ?", answer: "L'Ave Maria de Handel, émission de Reginald Fessenden (1906)" },
  { question: "Quel acteur hollywoodien est apparu dans le plus grand nombre de films au box-office mondial ?", answer: "Samuel L. Jackson (ses films totalisent plus de 27 milliards de dollars)" },
  { question: "En quelle année le premier SMS de l'histoire a-t-il été envoyé ?", answer: "1992 (le message était 'Merry Christmas')" },
  { question: "Quel est le film le plus court ayant remporté l'Oscar du meilleur film ?", answer: "Annie Hall de Woody Allen (1977, 93 minutes)" },
  { question: "Combien de membres compte l'Académie des Arts et Sciences du Cinéma (les Oscars) ?", answer: "Plus de 10 000 membres" },
  { question: "Quel est le premier pays à avoir interdit les publicités TV pour les enfants ?", answer: "La Suède (1991)" },
  { question: "Combien de fois la chanson 'Happy Birthday to You' est-elle chantée par jour dans le monde ?", answer: "Environ 2 millions de fois par jour" },
  { question: "Quel chanteur pop détient le record des albums les plus vendus en une seule semaine ?", answer: "Taylor Swift (toutes ses rééditions battent des records hebdomadaires depuis 2021)" },
  { question: "Quel film d'animation Disney a coûté le plus cher à produire ?", answer: "Raiponce (environ 260 millions de dollars, 2010)" },
  { question: "Combien de personnages différents Meryl Streep incarne-t-elle dans ses 50 ans de carrière ?", answer: "Plus de 60 rôles principaux distincts" },
  { question: "Quelle émission de TV a été regardée par le plus grand nombre de téléspectateurs simultanément ?", answer: "La finale de la Coupe du Monde 2022 (environ 1,5 milliard de téléspectateurs)" },

  // ══════════════════════════════════════════════════════════
  // SPORT — ANECDOTES INSOLITES (35)
  // ══════════════════════════════════════════════════════════
  { question: "Combien de fois Usain Bolt a-t-il battu le record du monde du 100m ?", answer: "3 fois (2008 Pékin, 2009 Berlin : 9,58s, record actuel)" },
  { question: "Quel pays a gagné une médaille d'or olympique sans aucune piscine sur son territoire ?", answer: "Éthiopie (nage synchronisée) — en réalité c'est Zimbabwe qui a gagné l'or en natation en 1980" },
  { question: "Combien de balles de tennis sont utilisées lors d'un tournoi de Wimbledon ?", answer: "Environ 54 000 balles" },
  { question: "Quel sportif a gagné le plus de médailles olympiques dans l'histoire ?", answer: "Michael Phelps (23 médailles d'or, 28 au total)" },
  { question: "En quelle année le football a-t-il été officiellement inclus aux Jeux Olympiques ?", answer: "1900 (Paris)" },
  { question: "Combien de fois par seconde un joueur de ping-pong frappe-t-il la balle lors d'un échange rapide ?", answer: "Jusqu'à 5 fois par seconde (balle à 170 km/h)" },
  { question: "Quelle est la vitesse maximale d'un service de tennis en km/h, record mondial ?", answer: "263,4 km/h (Sam Groth, Australie, 2012)" },
  { question: "Quel pays a remporté la Coupe du Monde de football le plus de fois ?", answer: "Le Brésil (5 fois)" },
  { question: "Combien de balles de golf sont perdues chaque année dans le monde ?", answer: "Environ 300 millions de balles par an" },
  { question: "Quel est le salaire annuel le plus élevé jamais versé à un sportif en activité ?", answer: "Environ 650 millions de dollars (Conor McGregor en 2021, Forbes)" },
  { question: "En quelle année les femmes ont-elles été autorisées à courir le marathon olympique ?", answer: "1984 (Los Angeles)" },
  { question: "Quel est le sport avec le taux de blessures le plus élevé au monde ?", answer: "Le rugby à XV (taux de blessures jusqu'à 218 pour 1 000 heures de jeu)" },
  { question: "Combien de miles a parcouru Forrest Gump dans sa course fictive autour des États-Unis ?", answer: "Environ 15 248 miles dans le film" },
  { question: "Quel judoka est le seul à avoir battu son propre record du monde à 3 Jeux Olympiques différents ?", answer: "Teddy Riner (mais c'est un sport de combat, il est triple champion olympique)" },
  { question: "Combien de km un joueur de football parcourt-il en moyenne par match ?", answer: "Environ 10 à 12 km" },
  { question: "Quelle est la durée du plus long match d'échecs jamais joué en tournoi officiel ?", answer: "20 heures 15 minutes (Nikolic vs Arsovic, 1989)" },
  { question: "Combien de personnes jouent régulièrement aux échecs dans le monde ?", answer: "Environ 600 millions de personnes" },
  { question: "Quel sportif a participé aux Jeux Olympiques dans deux sports différents la même année ?", answer: "Clara Hughes (cyclisme et patinage de vitesse, à des JO différents)" },
  { question: "Combien de matches a-t-il fallu à la France pour remporter son premier Mondial de football ?", answer: "7 matches (France 1998)" },
  { question: "Quelle est la vitesse maximale d'un lancer de baseball en km/h, record mondial ?", answer: "Environ 169 km/h (Aroldis Chapman)" },
  { question: "Combien de tour du monde représentent les km parcourus par un cycliste du Tour de France ?", answer: "Environ 3 500 km, soit moins d'un dixième du tour du monde" },
  { question: "En quelle année les Jeux Olympiques modernes ont-ils été fondés ?", answer: "1896 (Athènes, Grèce)" },
  { question: "Quel est le sport avec le plus de règles officielles au monde ?", answer: "Le cricket (lois du cricket — 42 règles très détaillées)" },
  { question: "Combien de calories brûle un marathonien pendant une course de 42 km ?", answer: "Environ 2 600 à 3 000 calories" },
  { question: "Quel footballeur a marqué le but le plus rapide de l'histoire de la Premier League ?", answer: "Shane Long (10,54 secondes, 2019)" },
  { question: "Combien de personnes ont terminé l'Iron Man d'Hawaii depuis sa création ?", answer: "Plus de 100 000 finishers depuis 1978" },
  { question: "Quelle est la longueur du plus long parcours de golf du monde ?", answer: "Environ 9 105 mètres (Nullarbor Links, Australie)" },
  { question: "Combien de joueurs de poker participent chaque année aux World Series of Poker Main Event ?", answer: "Environ 8 000 à 10 000 joueurs" },
  { question: "Quel est le sport le plus pratiqué par les femmes dans le monde ?", answer: "La natation" },
  { question: "Combien de temps dure le plus long plongeon en apnée statique, record mondial ?", answer: "24 minutes et 37 secondes (Budimir Šobat, 2021)" },
  { question: "Quel nageur a remporté 4 médailles d'or olympiques lors des mêmes Jeux en 1924 ?", answer: "Johnny Weissmuller (futur Tarzan au cinéma)" },
  { question: "Quelle est la pression exercée par un patineur artistique sur la lame de son patin ?", answer: "Plusieurs tonnes par cm² (environ 5 à 8 tonnes/cm² selon le poids)" },
  { question: "Combien de personnes courent le marathon de New York chaque année ?", answer: "Environ 50 000 coureurs" },
  { question: "Quel est le record du monde de sauts à la perche en hauteur ?", answer: "6,21 mètres (Armand Duplantis, 2024)" },
  { question: "Combien de grammes pèse une balle de golf réglementaire ?", answer: "45,93 grammes maximum" },

  // ══════════════════════════════════════════════════════════
  // LOIS ET RÈGLES INSOLITES (25)
  // ══════════════════════════════════════════════════════════
  { question: "Dans quel pays est-il légalement interdit de se faire prendre en photo à côté d'un panda ?", answer: "En Chine (les pandas sont propriété de l'État)" },
  { question: "Dans quel État américain est-il illégal de chasser les baleines, alors qu'il n'y a aucune côte ?", answer: "L'Oklahoma (une loi obsolète jamais abrogée)" },
  { question: "Dans quel pays est-il interdit par la loi de marcher dans les rues uniquement en maillot de bain ?", answer: "À Barcelone (Espagne) depuis 2011" },
  { question: "Dans quel pays est-il illégal de se suicider dans le Parlement ?", answer: "Au Royaume-Uni (considéré comme un lieu royal — loi jamais abrogée)" },
  { question: "Quel fruit est interdit dans les hôtels et les transports en commun à Singapour ?", answer: "Le durian (son odeur est légalement réglementée)" },
  { question: "Dans quel pays est-il obligatoire par loi de sourire en public sauf aux funérailles ?", answer: "À Tbilissi (Géorgie) — une ancienne ordonnance locale" },
  { question: "Dans quel pays peut-on légalement lancer des tomates sur des inconnus pendant un festival ?", answer: "En Espagne (La Tomatina, à Buñol)" },
  { question: "Dans quel pays est-il illégal d'importer des chewing-gums ?", answer: "À Singapour (sauf usage médical)" },
  { question: "Dans quel pays est-il interdit de nommer son enfant 'Superman' ?", answer: "En Nouvelle-Zélande (et dans de nombreux pays européens)" },
  { question: "Dans quel pays les nains de jardin sont-ils protégés par une association officielle anti-kidnapping ?", answer: "En France (le Front de Libération des Nains de Jardin existe réellement)" },
  { question: "Dans quel pays est-il illégal de marcher sur un billet de banque à cause de l'effigie royale ?", answer: "En Thaïlande" },
  { question: "Dans quel pays le ketchup est-il interdit dans les cantines scolaires pour protéger la gastronomie nationale ?", answer: "En France (interdit depuis 2011, sauf avec les frites)" },
  { question: "Quelle couleur de voiture est interdite à Paris par une loi jamais officiellement abrogée ?", answer: "Aucune — mais le rouge sang l'était dans plusieurs villes au XIXe siècle" },
  { question: "Dans quel pays est-il illégal de prendre des photos de bâtiments gouvernementaux ?", answer: "En Biélorussie et en Chine (très strictement appliqué)" },
  { question: "Dans quel pays peut-on légalement conduire à 14 ans sur route ouverte ?", answer: "En Islande (avec un adulte) et dans certains États américains (Montana, 15 ans)" },
  { question: "Dans quel pays est-il légalement interdit d'utiliser les congés maladie quand on est malade ?", answer: "En Slovaquie (historiquement, les congés maladie ne pouvaient pas être utilisés les week-ends)" },
  { question: "Dans quel pays est-il illégal de siffler après 22h ?", answer: "À Petrolia (Canada) — une loi municipale toujours valide" },
  { question: "Dans quel pays peut-on être arrêté pour avoir une Bible dans sa voiture ?", answer: "En Arabie Saoudite (possession de matériel religieux non-islamique est illégale)" },
  { question: "Dans quel pays est-il interdit de porter des talons hauts dans les sites archéologiques ?", answer: "En Grèce (pour protéger les monuments)" },
  { question: "Dans quel pays est-il légal de louer un mari ou une femme fictif pour un week-end ?", answer: "Au Japon (agences de 'famille à louer' légales depuis les années 2000)" },
  { question: "Dans quel pays est-il obligatoire de voter sous peine d'amende ?", answer: "En Australie (51 pays dans le monde ont le vote obligatoire)" },
  { question: "Dans quel pays est-il illégal de laisser son chien aboyer après 22h ?", answer: "En France (tapage nocturne, article R. 1334-31 du Code de la santé)" },
  { question: "Dans quel pays peut-on aller en prison pour avoir trop souri sur une photo d'identité ?", answer: "Nulle part — mais 12 pays dont le Canada interdisent de sourire sur les passeports" },
  { question: "Dans quel pays est-il illégal pour un homme de tricoter en public ?", answer: "Au Portugal — cette loi absurde existait sous Salazar et n'a jamais été formellement abrogée" },
  { question: "Dans quel pays un enfant né d'une mère non-mariée hérite automatiquement de deux pères légaux ?", answer: "En France (depuis 1804, le Code civil prévoyait le 'pater semper incertus')" },

  // ══════════════════════════════════════════════════════════
  // INVENTIONS & DÉCOUVERTES ACCIDENTELLES (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel aliment a été inventé accidentellement par un enfant qui avait laissé son bâtonnet dans un verre de soda ?", answer: "La sucette glacée (Frank Epperson, 1905, à 11 ans)" },
  { question: "Quelle invention majeure a été découverte par hasard par Percy Spencer en passant devant un tube radar ?", answer: "Le four à micro-ondes (sa barre de chocolat avait fondu, 1945)" },
  { question: "Quel matériau omniprésent aujourd'hui a été découvert par un chimiste qui cherchait un substitut au caoutchouc ?", answer: "La super-colle (cyanoacrylate), découverte accidentellement en 1942" },
  { question: "Quel médicament révolutionnaire a été découvert parce qu'un chercheur avait oublié une boîte de Petri en partant en vacances ?", answer: "La pénicilline (Alexander Fleming, 1928)" },
  { question: "Quelle boisson gazeuse a été inventée par un pharmacien qui cherchait un remède contre les maux de tête ?", answer: "Le Coca-Cola (John Pemberton, 1886)" },
  { question: "Quel célèbre jeu de société a été inventé par une femme seule pour critiquer le capitalisme ?", answer: "Le Monopoly (Elizabeth Magie, 1903, 'The Landlord's Game')" },
  { question: "Quelle découverte scientifique majeure a eu lieu parce qu'un physicien regardait des raies noires dans la lumière solaire ?", answer: "Le spectre d'absorption (Fraunhofer, 1814) — base de la spectroscopie" },
  { question: "Quel matériau révolutionnaire du XXe siècle a été découvert par un chimiste de DuPont en 1938 ?", answer: "Le Teflon (Roy Plunkett, découverte accidentelle)" },
  { question: "Quelle invention iconique est née parce qu'un ingénieur voulait coller des notes sans abîmer les partitions de son choeur ?", answer: "Le Post-it (Art Fry, 3M, 1974)" },
  { question: "Quel plastique très commun a été découvert par erreur par un chimiste qui voulait synthétiser un colorant ?", answer: "La Bakélite (Leo Baekeland, 1907)" },
  { question: "Quelle découverte médicale a été faite après qu'un médecin a remarqué que ses patients diabétiques avaient des urines attirantes pour les insectes ?", answer: "La distinction entre diabète de type 1 et 2 et le rôle du sucre dans l'urine" },
  { question: "Quelle technologie de communication moderne a été inventée par une actrice de Hollywood pendant la Seconde Guerre mondiale ?", answer: "L'étalement de spectre (ancêtre du Wi-Fi/Bluetooth) — Hedy Lamarr, 1942" },
  { question: "Quel aliment très populaire a été inventé par un médecin qui cherchait un aliment sain sans mastication pour ses patients ?", answer: "Les Corn Flakes (Dr John Harvey Kellogg, 1894)" },
  { question: "Quelle invention utilisée des milliards de fois par jour a été créée par un ingénieur frustré de ne pas trouver ses skis dans la neige ?", answer: "Le velcro (George de Mestral, 1941, inspiré des bardanes)" },
  { question: "Quelle substance largement utilisée dans les cosmétiques a été découverte par un chimiste qui faisait frire du plastique ?", answer: "Le PTFE (Teflon) — utilisé dans les cosmétiques comme agent lissant" },
  { question: "Quel instrument de navigation a été inventé accidentellement par un horloger cherchant à mesurer le temps avec précision ?", answer: "Le chronomètre de marine (John Harrison, H4, 1759)" },
  { question: "Quelle couleur de tissu synthétique a été découverte par un chimiste de 18 ans qui expérimentait avec du goudron de houille ?", answer: "La mauvéine (premier colorant synthétique, William Perkin, 1856) — couleur mauve/violet" },
  { question: "Quel médicament très courant a été découvert parce qu'un chimiste avait les mains qui arrêtaient de transpirer ?", answer: "Le Botox (dérivé de la toxine botulique — découverte accidentelle sur ses effets cosmétiques)" },
  { question: "Quel aliment industriel a été créé à l'origine pour remplacer le beurre sur commande de Napoléon III ?", answer: "La margarine (Hippolyte Mège-Mouriès, 1869)" },
  { question: "Quel médicament a été développé pour traiter l'hypertension avant de révéler des effets secondaires inattendus très rentables ?", answer: "Le Viagra (sildénafil, Pfizer, 1998 — prévu pour l'angine de poitrine)" },
  { question: "Quelle matière plastique ultra-légère a été découverte par accident lors d'expériences sur l'éthylène sous haute pression ?", answer: "Le polyéthylène (PE, ICI, 1933)" },
  { question: "Quelle technologie de scan médicale a été découverte grâce à un physicien qui observait que ses clés brillaient dans le noir ?", answer: "Les rayons X (Wilhelm Röntgen, 1895)" },
  { question: "Quel jeu de réflexion numérique est né dans l'esprit d'un enseignant soviétique qui cherchait un outil pédagogique ?", answer: "Le Tetris (Alexeï Pajitnov, 1984, URSS)" },
  { question: "Quelle boisson chaude est devenue un empire industriel parce qu'un marchand portugais avait ramené des graines de Chine ?", answer: "Le thé en Europe (importé via la route des épices au XVIIe siècle)" },
  { question: "Quel médicament très courant contre la douleur a été synthétisé par un chimiste d'une entreprise d'explosifs ?", answer: "L'aspirine (Felix Hoffmann, Bayer, 1897 — Bayer fabriquait aussi de l'héroïne)" },

  // ══════════════════════════════════════════════════════════
  // PSYCHOLOGIE & COMPORTEMENT HUMAIN (25)
  // ══════════════════════════════════════════════════════════
  { question: "Comment s'appelle l'illusion qui fait qu'on pense être meilleur que la moyenne dans 93% des cas ?", answer: "L'effet Dunning-Kruger (les incompétents surestiment leurs compétences)" },
  { question: "Quel pourcentage des décisions humaines sont prises de manière inconsciente selon les neurosciences ?", answer: "Environ 95% des décisions sont inconscientes" },
  { question: "Comment s'appelle le phénomène où on dépense plus après une petite dépense initiale ?", answer: "L'effet de porte-dans-le-pied (foot-in-the-door)" },
  { question: "Quel est le phénomène psychologique qui explique qu'on aime plus ce qu'on possède que ce qu'on désire ?", answer: "L'effet de dotation (endowment effect)" },
  { question: "Comment s'appelle l'effet qui fait qu'on juge les gens plus intelligents s'ils portent des lunettes ?", answer: "Le biais de l'effet de halo" },
  { question: "Quelle est la durée maximale de concentration intense possible sans pause selon les études cognitives ?", answer: "Environ 90 minutes (cycle ultradien)" },
  { question: "Comment s'appelle la tendance à chercher uniquement des informations qui confirment nos opinions ?", answer: "Le biais de confirmation" },
  { question: "Quel pourcentage du langage humain est non-verbal selon Albert Mehrabian ?", answer: "55% corporel, 38% ton de voix, 7% mots" },
  { question: "Comment s'appelle le phénomène où la présence d'autres personnes nous rend moins enclins à aider quelqu'un ?", answer: "L'effet du spectateur (bystander effect)" },
  { question: "Quelle illusion d'optique célèbre montre une vieille femme ou une jeune femme selon la perception ?", answer: "L'illusion de la vieille et de la jeune femme (W.E. Hill, 1915)" },
  { question: "Comment s'appelle le biais qui fait qu'on préfère la deuxième option dans une liste de trois choix ?", answer: "L'effet de compromis (ou effet de domination asymétrique)" },
  { question: "Quelle est la taille d'un réseau social humain stable selon la théorie de Robin Dunbar ?", answer: "150 personnes (nombre de Dunbar)" },
  { question: "Comment s'appelle le phénomène où une idée fausse répétée assez souvent devient vraie dans notre esprit ?", answer: "L'effet de vérité illusoire (illusory truth effect)" },
  { question: "Quel pourcentage de nos pensées seraient répétitives d'un jour à l'autre selon une étude de 2020 ?", answer: "Environ 90% de nos pensées sont identiques à celles de la veille" },
  { question: "Comment s'appelle l'effet psychologique qui explique pourquoi on aime les produits chers même s'ils sont identiques ?", answer: "L'effet de prix-qualité (price-quality heuristic)" },
  { question: "Quel phénomène explique que les gens courent moins vite seuls qu'en groupe ?", answer: "C'est l'inverse — l'effet d'audience améliore les performances simples (effet Zajonc)" },
  { question: "Comment s'appelle la peur irrationnelle d'être sans batterie ou sans réseau sur son téléphone ?", answer: "La nomophobie (no mobile phobia)" },
  { question: "Quel est le terme pour décrire la satisfaction perverse qu'on ressent face au malheur des autres ?", answer: "La schadenfreude (mot allemand)" },
  { question: "Comment s'appelle le biais cognitif qui nous fait surestimer notre rôle dans les succès collectifs ?", answer: "Le biais d'auto-complaisance (self-serving bias)" },
  { question: "Quel phénomène explique qu'on dépense plus facilement avec une carte bancaire qu'en cash ?", answer: "Le découplage du paiement (decoupling) — la douleur de payer est atténuée" },
  { question: "Comment s'appelle l'illusion qui fait croire que tout le monde pense pareil à nous ?", answer: "L'effet de faux consensus (false consensus effect)" },
  { question: "Quel effet psychologique explique que les gens gardent un investissement raté plutôt que d'abandonner ?", answer: "Le biais des coûts irrécupérables (sunk cost fallacy)" },
  { question: "Comment s'appelle le phénomène où on est plus créatif quand on travaille pour quelqu'un d'autre que pour soi ?", answer: "L'effet Salomon (ou 'Solomon's paradox')" },
  { question: "Quel est le terme pour désigner la tristesse vague qu'on ressent sans raison particulière ?", answer: "La 'langueur' (languishing, popularisé par Adam Grant en 2021)" },
  { question: "Comment s'appelle le phénomène où on finit par ressembler physiquement à ses proches après des années de vie commune ?", answer: "La convergence phénotypique (démontré par une étude de l'Université de Michigan, 1987)" },

  // ══════════════════════════════════════════════════════════
  // ARGENT, ÉCONOMIE & CURIOSITÉS FINANCIÈRES (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quelle est la dette publique américaine arrondie au trillion de dollars en 2024 ?", answer: "Environ 34 000 milliards de dollars (34 trillions)" },
  { question: "Quel billet de banque est le plus répandu dans le monde ?", answer: "Le billet de 1 dollar américain" },
  { question: "Combien coûte une action Berkshire Hathaway de classe A (Warren Buffet) ?", answer: "Environ 600 000 dollars (l'action la plus chère du monde)" },
  { question: "Quel pays a connu l'hyperinflation la plus extrême de l'histoire, avec des billets de 100 000 milliards ?", answer: "Le Zimbabwe (2008-2009)" },
  { question: "Combien de milliards de dollars perdent chaque année les Américains dans les parkings de jeux ?", answer: "Environ 120 milliards de dollars par an (Vegas + casinos)" },
  { question: "Quelle est la fortune estimée de la famille royale britannique ?", answer: "Environ 28 milliards de dollars (la Couronne britannique)" },
  { question: "Combien de dollars vaut une pièce de 25 cents (quarter) si elle est frappée en argent pur avant 1964 ?", answer: "Environ 4 à 5 dollars (valeur métallique)" },
  { question: "Quel pays possède les plus grandes réserves d'or au monde ?", answer: "Les États-Unis (environ 8 133 tonnes à Fort Knox et ailleurs)" },
  { question: "Combien de temps faut-il à un humain travaillant au SMIC français pour gagner ce qu'Elon Musk gagne en une seconde ?", answer: "Environ 1 an de travail au SMIC = 1 seconde du revenu de Musk (à son apogée)" },
  { question: "Quel est le pays avec le PIB le plus bas au monde par habitant ?", answer: "Le Burundi (environ 260 dollars par an par habitant)" },
  { question: "Combien de billets de banque la Fed américaine imprime-t-elle chaque jour ?", answer: "Environ 38 millions de billets par jour" },
  { question: "Quelle est la monnaie qui a le taux de change le plus élevé face à l'euro ?", answer: "Le dinar koweïtien (1 KWD ≈ 3 euros)" },
  { question: "Combien de fois la fortune de Jeff Bezos a-t-elle été supérieure au PIB d'un pays entier ?", answer: "Sa fortune dépasse le PIB de 140 pays sur 195 (2021)" },
  { question: "Quelle est la fraude financière la plus grande de l'histoire des États-Unis ?", answer: "L'arnaque Ponzi de Bernie Madoff (environ 65 milliards de dollars)" },
  { question: "Combien de milliards vaut l'industrie du luxe mondiale ?", answer: "Environ 1 500 milliards de dollars (2023)" },
  { question: "Quelle entreprise a été la première à atteindre 1 000 milliards de dollars de capitalisation boursière ?", answer: "Apple (2018)" },
  { question: "Combien de fois par an change-t-on en moyenne d'emploi dans une vie en France ?", answer: "Environ 15 à 20 fois dans une carrière" },
  { question: "Quel est le prix du mètre carré le plus cher au monde ?", answer: "À Monaco (environ 50 000 euros le m²)" },
  { question: "Combien de milliards de transactions par carte bancaire ont lieu chaque jour dans le monde ?", answer: "Environ 1,1 milliard de transactions par jour" },
  { question: "Quelle est la somme la plus grande jamais braquée dans une banque ?", answer: "Environ 1 milliard de dollars (Saddam Hussein, Central Bank of Iraq, 2003)" },
  { question: "Combien de milliards de dollars valent les œuvres d'art vendues chaque année dans le monde ?", answer: "Environ 65 milliards de dollars" },
  { question: "Quel est le prix de vente record d'un tableau aux enchères ?", answer: "Salvator Mundi de Léonard de Vinci : 450 millions de dollars (2017)" },
  { question: "Combien d'euros la France a-t-elle reçu pour vendre la Louisiane aux États-Unis ?", answer: "Environ 15 millions de dollars de l'époque (1803), soit ~320 millions aujourd'hui" },
  { question: "Quelle est la valeur estimée du Bitcoin au plus haut de son histoire en dollars ?", answer: "Environ 73 000 dollars (mars 2024)" },
  { question: "Combien de milliards de dollars rapporte l'industrie des jeux vidéo par an, dépassant Hollywood ?", answer: "Environ 200 milliards de dollars (vs 100 milliards pour le cinéma)" },

  // ══════════════════════════════════════════════════════════
  // FRANCE — ANECDOTES INSOLITES (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est le seul animal à avoir été officiellement naturalisé français par décret ?", answer: "Le canard de Barbarie (via une ancienne ordonnance de classification zoologique)" },
  { question: "Combien de lois et règlements la France produit-elle en moyenne par an ?", answer: "Environ 10 000 textes législatifs et réglementaires par an" },
  { question: "Quel est le fromage français le plus imité dans le monde ?", answer: "Le Brie" },
  { question: "Combien de baguettes de pain sont vendues chaque jour en France ?", answer: "Environ 30 millions de baguettes par jour" },
  { question: "En quelle année la France a-t-elle officiellement adopté le système métrique ?", answer: "1795 (mais généralisé à partir de 1840)" },
  { question: "Quel célèbre monument parisien était initialement prévu pour être démonté après 20 ans ?", answer: "La Tour Eiffel (construite en 1889 pour l'Exposition universelle)" },
  { question: "Combien de châteaux et manoirs compte le territoire français ?", answer: "Environ 45 000 châteaux et manoirs" },
  { question: "Quelle est la région française qui produit le plus de vin ?", answer: "La Nouvelle-Aquitaine (Bordeaux en tête)" },
  { question: "Combien de kilomètres de côtes la France possède-t-elle au total ?", answer: "Environ 5 500 km de côtes métropolitaines" },
  { question: "Quel est le vrai nom de famille de Molière ?", answer: "Jean-Baptiste Poquelin" },
  { question: "En quelle année la France a-t-elle adopté l'heure d'été ?", answer: "1976 (suite au choc pétrolier de 1973)" },
  { question: "Combien de langues régionales sont parlées en France métropolitaine ?", answer: "Plus de 75 langues et dialectes régionaux" },
  { question: "Quel département français est le plus grand par superficie ?", answer: "La Guyane française (83 534 km², un département d'outre-mer)" },
  { question: "Combien de maires y a-t-il en France, pays qui en compte le plus au monde ?", answer: "Environ 35 000 maires" },
  { question: "Quelle est la superficie de Paris en km², la ville intra-muros ?", answer: "Environ 105 km² (plus petite que beaucoup de villes françaises)" },
  { question: "En quelle année les Français ont-ils obtenu le droit de travailler le dimanche dans les grandes surfaces ?", answer: "2009 (loi Mallié)" },
  { question: "Quel est le prénom le plus donné en France sur les 100 dernières années ?", answer: "Marie (pour les femmes) et Jean (pour les hommes)" },
  { question: "Combien de bises font les Français en moyenne pour se saluer, et varie-t-il selon les régions ?", answer: "Entre 1 et 4 bisous selon la région (2 en Île-de-France, 3 dans le Sud)" },
  { question: "Quel produit français est interdit à l'exportation vers les États-Unis depuis 2004 pour raisons sanitaires ?", answer: "Le Roquefort (à plusieurs reprises — la FDA bloque certains fromages au lait cru)" },
  { question: "En quelle année la France a-t-elle légalisé le port du pantalon pour les femmes à Paris ?", answer: "2013 (abrogation d'une ordonnance de 1800 qui l'interdisait)" },
  { question: "Combien de variétés de pain différentes peut-on trouver dans les boulangeries françaises ?", answer: "Plus de 400 variétés officiellement recensées" },
  { question: "Quel est le seul animal sauvage encore chassé en France malgré une protection européenne ?", answer: "L'ortolan (interdit mais toléré dans certaines régions jusqu'à récemment)" },
  { question: "Combien de Français déclarent ne pas aimer le fromage, selon les sondages ?", answer: "Environ 10% des Français (contre 95% qui en consomment régulièrement)" },
  { question: "Quelle est la durée légale maximum d'une garde à vue en France ?", answer: "24 heures (extensible à 48 heures, voire 96 heures pour terrorisme)" },
  { question: "En quelle année Napoléon a-t-il rendu le divorce légal en France ?", answer: "1804 (Code civil — il l'avait d'abord instauré en 1792 lors de la Révolution)" },

];

module.exports = { questions };
