// 305 questions — toutes notées ≥ 8/10 en difficulté, insolites et vérifiées.

const questions = [

  // ══════════════════════════════════════════
  // ANIMAUX — conservées de l'original (24)
  // ══════════════════════════════════════════
  { question: "Combien de dents possède un escargot adulte ?", answer: "Plus de 14 000" },
  { question: "Combien d'yeux possède une abeille ?", answer: "5 yeux" },
  { question: "Combien d'heures dort un koala par jour ?", answer: "Entre 18 et 22 heures" },
  { question: "Combien de dents utilise un requin dans toute sa vie ?", answer: "Jusqu'à 50 000" },
  { question: "Combien de muscles possède la trompe d'un éléphant ?", answer: "Plus de 40 000" },
  { question: "De quelle couleur est la sueur d'un hippopotame ?", answer: "Rose" },
  { question: "Combien de battements par seconde fait un colibri de ses ailes ?", answer: "Jusqu'à 80 battements" },
  { question: "Quel est le plus venimeux animal marin du monde ?", answer: "La pieuvre à anneaux bleus" },
  { question: "Quelle est la durée de vie moyenne d'un ver de terre ?", answer: "Entre 4 et 8 ans" },
  { question: "Quelle est la taille maximale d'un ver de mer géant ?", answer: "Jusqu'à 3 mètres" },
  { question: "Quel mammifère marin peut rester en apnée le plus longtemps ?", answer: "Le cachalot (jusqu'à 2 heures)" },
  { question: "Combien de types de dents possède un crocodile ?", answer: "1 seul type (coniques)" },
  { question: "Quel est le plus rapide animal marin ?", answer: "Le voilier (110 km/h)" },
  { question: "Quel insecte peut soulever 850 fois son propre poids ?", answer: "Le scarabée rhinocéros" },
  { question: "Quel animal produit la soie la plus résistante ?", answer: "L'araignée Darwin (10 fois plus résistante que le Kevlar)" },
  { question: "Combien de km/h peut atteindre un faucon pèlerin en plongée ?", answer: "Jusqu'à 390 km/h" },
  { question: "Combien d'yeux possède un limule (crabe fer à cheval) ?", answer: "10 yeux" },
  { question: "Quel animal peut se régénérer entièrement même après avoir été coupé en deux ?", answer: "Le ver plat (planaire)" },
  { question: "Combien d'espèces de pingouins existe-t-il ?", answer: "18 espèces" },
  { question: "Quel est le seul continent sans abeilles indigènes ?", answer: "L'Antarctique" },
  { question: "Combien de km un saumon remonte-t-il pour frayer ?", answer: "Jusqu'à 1 500 km" },
  { question: "Quel animal est l'hôte de la majorité des parasites connus ?", answer: "Le rat brun" },
  { question: "Quel oiseau peut imiter jusqu'à 200 sons différents ?", answer: "L'oiseau-lyre (Australie)" },
  { question: "Combien d'espèces de chauves-souris existe-t-il ?", answer: "Plus de 1 400 espèces" },

  // ══════════════════════════════════════════
  // GÉOGRAPHIE — conservées (13)
  // ══════════════════════════════════════════
  { question: "Quel pays possède le plus de fuseaux horaires ?", answer: "La France (12 fuseaux)" },
  { question: "Quelle mer n'a aucun rivage ?", answer: "La mer des Sargasses" },
  { question: "Quel est le pays le plus chaud du monde ?", answer: "Le Mali" },
  { question: "Quelle est la ville la plus froide du monde habitée en permanence ?", answer: "Oïmiakon (Russie, -67°C)" },
  { question: "Quel pays est traversé par le plus de pays frontaliers ?", answer: "La Chine (14 voisins)" },
  { question: "Quelle est la montagne la plus haute du système solaire ?", answer: "Olympus Mons (Mars, 21 km)" },
  { question: "Dans quel pays se trouve le désert de Gobi ?", answer: "Entre la Chine et la Mongolie" },
  { question: "Quel est le plus grand désert du monde ?", answer: "L'Antarctique (désert froid)" },
  { question: "Combien de pays composent le continent africain ?", answer: "54 pays" },
  { question: "Quel pays possède la plus longue côte maritime du monde ?", answer: "Le Canada" },
  { question: "Quelle est la ville la plus haute du monde ?", answer: "La Rinconada (Pérou, 5 100 m)" },
  { question: "Quel est le plus grand lac du monde ?", answer: "La mer Caspienne (techniquement un lac)" },
  { question: "Quel pays possède le plus grand nombre d'îles ?", answer: "La Suède (221 000 îles)" },

  // ══════════════════════════════════════════
  // SCIENCES — conservées (16)
  // ══════════════════════════════════════════
  { question: "À quelle température l'eau bout-elle au sommet de l'Everest ?", answer: "Environ 70°C" },
  { question: "Quel est le métal le plus léger du monde ?", answer: "Le lithium" },
  { question: "Combien de cellules contient le corps humain ?", answer: "Environ 37 000 milliards" },
  { question: "Quel est le seul métal liquide à température ambiante (hormis le mercure) ?", answer: "Le gallium (fond à 29°C)" },
  { question: "Quelle planète tourne sur elle-même dans le sens inverse des autres ?", answer: "Vénus (et Uranus)" },
  { question: "Combien de tonnes de météorites tombent sur Terre chaque jour ?", answer: "Environ 80 tonnes" },
  { question: "À quelle vitesse tourne la Terre sur son axe à l'équateur ?", answer: "Environ 1 670 km/h" },
  { question: "Combien de grammes de bactéries vit-on dans notre intestin ?", answer: "Environ 1 500 grammes" },
  { question: "Quelle est la durée d'un jour sur Vénus ?", answer: "243 jours terrestres" },
  { question: "Quelle est la température au centre de la Terre ?", answer: "Environ 6 000°C" },
  { question: "Combien de secondes dure une année ?", answer: "Environ 31,5 millions de secondes" },
  { question: "Combien de neurones contient le cerveau humain ?", answer: "Environ 86 milliards" },
  { question: "Quelle est la durée de vie d'un globule rouge ?", answer: "Environ 120 jours" },
  { question: "Combien de fois l'être humain cligne des yeux par jour ?", answer: "Environ 15 000 fois" },
  { question: "Quelle est la fréquence des battements cardiaques d'un nouveau-né ?", answer: "Entre 120 et 160 battements/min" },
  { question: "Quel est le point de fusion de l'or ?", answer: "1 064°C" },

  // ══════════════════════════════════════════
  // CORPS HUMAIN — conservées (12)
  // ══════════════════════════════════════════
  { question: "Quelle est la longueur totale des vaisseaux sanguins humains ?", answer: "Environ 100 000 km" },
  { question: "Combien de litres de salive produit-on par jour ?", answer: "Entre 1 et 1,5 litres" },
  { question: "Quelle est la longueur de l'intestin grêle ?", answer: "Entre 6 et 7 mètres" },
  { question: "Combien de poils compte en moyenne un être humain sur son corps ?", answer: "Environ 5 millions de poils" },
  { question: "À quelle vitesse l'information circule-t-elle dans les nerfs ?", answer: "Jusqu'à 430 km/h" },
  { question: "Combien d'os y a-t-il dans la main humaine ?", answer: "27 os" },
  { question: "Quelle est la durée de vie d'un globule blanc ?", answer: "De quelques heures à quelques jours" },
  { question: "Quel est le seul organe qui peut se régénérer entièrement ?", answer: "Le foie" },
  { question: "Combien de bactéries vit-on dans notre bouche ?", answer: "Entre 500 et 1 000 espèces différentes" },
  { question: "Quelle est la longueur de l'ADN contenu dans une seule cellule humaine ?", answer: "Environ 2 mètres" },
  { question: "Combien d'os a un bébé à sa naissance ?", answer: "Environ 270 à 300 os" },
  { question: "Combien de litres d'air inspire-t-on par jour ?", answer: "Environ 11 000 litres" },

  // ══════════════════════════════════════════
  // HISTOIRE — conservées (4)
  // ══════════════════════════════════════════
  { question: "Combien de temps a duré la guerre de Cent Ans ?", answer: "116 ans (1337-1453)" },
  { question: "Combien de pyramides se trouvent en Égypte ?", answer: "Plus de 130" },
  { question: "Quelle civilisation a inventé l'écriture ?", answer: "Les Sumériens (cunéiforme)" },
  { question: "Quelle est la durée du règne de Louis XIV ?", answer: "72 ans (le plus long d'Europe)" },

  // ══════════════════════════════════════════
  // ALIMENTATION — conservées (11)
  // ══════════════════════════════════════════
  { question: "Quel fruit contient le plus de vitamine C ?", answer: "L'acérola (40 fois plus que l'orange)" },
  { question: "Dans quel pays le chocolat a-t-il été inventé ?", answer: "Au Mexique (civilisation aztèque)" },
  { question: "De quelle plante provient la vanille ?", answer: "D'une orchidée (Vanilla planifolia)" },
  { question: "Quel pays est le plus grand producteur de lait au monde ?", answer: "L'Inde" },
  { question: "Combien de sortes d'olives existe-t-il dans le monde ?", answer: "Plus de 2 000 variétés" },
  { question: "Quel est le fromage le plus consommé dans le monde ?", answer: "La mozzarella" },
  { question: "Quel fruit est à la fois un fruit, une baie et une drupe selon les botanistes ?", answer: "L'avocat" },
  { question: "Combien de grains de café faut-il pour faire un expresso ?", answer: "Environ 50 à 70 grains" },
  { question: "De quelle couleur est la carotte originellement ?", answer: "Violette ou blanche (pas orange)" },
  { question: "Combien de variétés de bananes existe-t-il ?", answer: "Plus de 1 000 variétés" },
  { question: "Quel pays boit le plus de thé par habitant ?", answer: "La Turquie" },

  // ══════════════════════════════════════════
  // DIVERS — conservées (10)
  // ══════════════════════════════════════════
  { question: "Combien de langues sont parlées dans le monde ?", answer: "Environ 7 100 langues" },
  { question: "Quel est le prénom le plus donné dans le monde ?", answer: "Mohamed (sous toutes ses orthographes)" },
  { question: "Quel pays a les habitants les plus grands du monde ?", answer: "Les Pays-Bas" },
  { question: "Combien de briques composent la Grande Muraille de Chine ?", answer: "Environ 3 873 000 000 briques" },
  { question: "Quel est le livre le plus vendu de l'Histoire après la Bible ?", answer: "Le Petit Prince" },
  { question: "Combien de marches compte la Tour Eiffel jusqu'au sommet ?", answer: "1 665 marches" },
  { question: "Combien de fois la Tour Eiffel change-t-elle de taille entre l'hiver et l'été ?", answer: "Jusqu'à 15 cm de différence" },
  { question: "Quel pays a les meilleures performances scolaires selon PISA ?", answer: "Singapour (régulièrement premier)" },
  { question: "Combien de volcans actifs y a-t-il sur Terre ?", answer: "Environ 1 500" },
  { question: "Combien d'avions sont en vol en même temps dans le monde en temps normal ?", answer: "Environ 10 000" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — ANIMAUX (35)
  // ══════════════════════════════════════════════════════════
  { question: "Combien d'années un escargot peut-il dormir d'affilée en cas de sécheresse ?", answer: "Jusqu'à 3 ans" },
  { question: "Combien de couleurs une crevette-mante peut-elle distinguer ?", answer: "16 couleurs (contre 3 pour l'humain)" },
  { question: "Quel grand mammifère est physiologiquement incapable de vomir ?", answer: "Le cheval" },
  { question: "Combien d'œufs pond une reine termite par jour ?", answer: "Jusqu'à 30 000 œufs" },
  { question: "Quel animal produit le son le plus fort sur Terre ?", answer: "La baleine bleue (jusqu'à 188 décibels)" },
  { question: "Combien d'espèces de fourmis existent sur Terre ?", answer: "Plus de 20 000 espèces" },
  { question: "Quelle créature adulte ne vit que quelques heures, le temps de se reproduire ?", answer: "La mouche éphémère" },
  { question: "Combien d'années un tardigrade peut-il survivre sans eau ni nourriture ?", answer: "Jusqu'à 30 ans" },
  { question: "Quel grand reptile peut se reproduire sans mâle par parthénogenèse ?", answer: "Le dragon de Komodo (femelle)" },
  { question: "Combien de facettes possède l'œil d'une libellule ?", answer: "Environ 30 000 facettes par œil" },
  { question: "Quel animal cause le plus de décès humains par an dans le monde ?", answer: "Le moustique (plus de 750 000 morts/an)" },
  { question: "Combien de battements par minute a le cœur d'un colibri en vol actif ?", answer: "Jusqu'à 1 200 battements/min" },
  { question: "Quelle est la durée de gestation d'une éléphante ?", answer: "22 mois (la plus longue des mammifères terrestres)" },
  { question: "Combien de fois son propre poids une fourmi peut-elle porter ?", answer: "50 fois son propre poids" },
  { question: "Quel animal possède des empreintes digitales impossibles à distinguer de celles de l'humain ?", answer: "Le koala" },
  { question: "Quelle méduse peut revenir à l'état de larve après maturité, la rendant théoriquement immortelle ?", answer: "Turritopsis dohrnii" },
  { question: "Quel animal peut survivre à des doses de radiation 500 fois mortelles pour l'humain ?", answer: "Le tardigrade" },
  { question: "Combien d'espèces d'oiseaux recense-t-on sur Terre ?", answer: "Environ 10 000 espèces" },
  { question: "Quel animal change entièrement de squelette chaque année en muant ?", answer: "Le homard" },
  { question: "Combien de litres de sang le cœur d'une baleine bleue propulse-t-il à chaque battement ?", answer: "Environ 220 litres" },
  { question: "Quelle carpe japonaise a vécu 226 ans, record documenté de longévité ?", answer: "La carpe koï Hanako (1751-1977)" },
  { question: "Quel oiseau peut voler sans s'arrêter pendant 10 mois ?", answer: "Le martinet noir" },
  { question: "Combien de mètres de fil de soie un ver à soie produit-il pour former son cocon ?", answer: "Jusqu'à 1 500 mètres" },
  { question: "Quel animal a le sang le plus précieux au monde, utilisé en médecine, à environ 15 000€ le litre ?", answer: "Le limule (crabe fer à cheval)" },
  { question: "Combien d'années vit un poulpe en moyenne, malgré son intelligence ?", answer: "Seulement 1 à 2 ans" },
  { question: "Combien de millions de fleurs une abeille doit-elle visiter pour produire 500 g de miel ?", answer: "Environ 2 millions de fleurs" },
  { question: "Quel est l'animal le plus électrique du monde ?", answer: "L'anguille électrique (jusqu'à 800 volts)" },
  { question: "Combien de mois une tortue géante peut-elle rester sans manger ni boire ?", answer: "Jusqu'à 18 mois" },
  { question: "Quel animal a la morsure la plus puissante au monde ?", answer: "Le crocodile du Nil (jusqu'à 2 000 kg de pression)" },
  { question: "Combien de dents possède une limace dans la bouche ?", answer: "Jusqu'à 27 000" },
  { question: "Quel est le seul mammifère dépourvu de dents adultes ?", answer: "L'ornithorynque adulte" },
  { question: "À quelle vitesse la langue d'un caméléon se déploie-t-elle ?", answer: "Elle atteint 97 km/h en 0,07 seconde" },
  { question: "Combien de mètres de cumulé représentent les fils de toile d'une araignée dans une seule nuit ?", answer: "Jusqu'à 30 mètres de fil" },
  { question: "Quel animal peut régénérer son propre cœur après une blessure ?", answer: "Le poisson zèbre" },
  { question: "Combien d'années peut vivre une reine des termites ?", answer: "Jusqu'à 50 ans" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — SCIENCES (35)
  // ══════════════════════════════════════════════════════════
  { question: "Combien pèse un nuage d'orage de taille moyenne ?", answer: "Environ 500 tonnes" },
  { question: "De combien la Lune s'éloigne-t-elle de la Terre chaque année ?", answer: "De 3,8 cm" },
  { question: "Quelle est la température de surface du Soleil ?", answer: "Environ 5 500°C" },
  { question: "Quel est l'élément le plus dense naturellement présent sur Terre ?", answer: "L'osmium" },
  { question: "À quelle vitesse se déplacent les plaques tectoniques ?", answer: "Entre 2 et 15 cm par an" },
  { question: "Quelle fraction d'un atome est occupée par de la matière (le reste étant vide) ?", answer: "Environ 0,0001%" },
  { question: "À quelle distance en km l'explosion du Krakatoa a-t-elle été entendue en 1883 ?", answer: "Jusqu'à 4 800 km" },
  { question: "Combien de km/h font les ondes sismiques dans la roche ?", answer: "Jusqu'à 13 000 km/h" },
  { question: "Quel métal a le point de fusion le plus élevé ?", answer: "Le tungstène (3 422°C)" },
  { question: "Combien d'années-lumière met-on pour traverser la Voie Lactée ?", answer: "Environ 100 000 années-lumière" },
  { question: "Combien de fois par jour la foudre frappe-t-elle la Terre ?", answer: "Environ 8 millions de fois" },
  { question: "Quel est le point d'ébullition de l'azote liquide ?", answer: "-196°C" },
  { question: "Combien de fois plus puissante était la Tsar Bomba soviétique que la bombe d'Hiroshima ?", answer: "Environ 3 300 fois" },
  { question: "Combien de neutrinos traversent votre corps chaque seconde ?", answer: "Environ 100 milliards de milliards" },
  { question: "Quelle est la durée de vie restante estimée du Soleil ?", answer: "Environ 5 milliards d'années" },
  { question: "Combien de tonnes de poussière interstellaire la Terre accumule-t-elle chaque année ?", answer: "Environ 40 000 tonnes" },
  { question: "Combien de types de quarks différents existe-t-il en physique des particules ?", answer: "6 types" },
  { question: "Quel est le métal le plus conducteur de l'électricité ?", answer: "L'argent" },
  { question: "Quelle est la durée de demi-vie du plutonium 239 ?", answer: "Environ 24 000 ans" },
  { question: "Combien de fois la Terre tient-elle dans le volume du Soleil ?", answer: "Environ 1,3 million de fois" },
  { question: "À quelle vitesse les informations voyagent-elles dans une fibre optique ?", answer: "Environ 200 000 km/s (2/3 de la vitesse de la lumière)" },
  { question: "Quelle est la pression au fond de la fosse des Mariannes ?", answer: "Environ 1 100 bars (1 100 fois la pression atmosphérique)" },
  { question: "Combien de fois la lumière fait-elle le tour de la Terre en une seconde ?", answer: "7,5 fois" },
  { question: "Quelle est la température minimale possible dans l'univers ?", answer: "-273,15°C (le zéro absolu)" },
  { question: "Combien d'atomes d'hydrogène contient un verre d'eau de 250 ml ?", answer: "Environ 17 billions de milliards d'atomes" },
  { question: "Quel est le seul liquide qui ne gèle pas même à des températures extrêmes sous pression ?", answer: "L'hélium superfluide" },
  { question: "Combien de km/h atteignent les vents de la Grande Tache Rouge de Jupiter ?", answer: "Jusqu'à 540 km/h" },
  { question: "Quelle planète a une journée plus longue que son année ?", answer: "Vénus (243 jours/jour vs 225 jours/an)" },
  { question: "Combien de fois la Voie Lactée et la galaxie d'Andromède sont-elles amenées à fusionner ?", answer: "Dans environ 4,5 milliards d'années" },
  { question: "Quel est le son le plus grave jamais détecté dans l'univers ?", answer: "Le bourdonnement d'un trou noir (57 octaves sous le do médian)" },
  { question: "Combien de km/s le Soleil se déplace-t-il dans la Voie Lactée ?", answer: "Environ 220 km/s" },
  { question: "Quelle est la durée de demi-vie du carbone 14, utilisé pour dater les fossiles ?", answer: "Environ 5 730 ans" },
  { question: "Combien pèse l'atmosphère terrestre en tonnes ?", answer: "Environ 5 millions de milliards de tonnes" },
  { question: "Quel est le gaz le plus rare dans l'air que l'on respire ?", answer: "Le xénon (environ 0,000009%)" },
  { question: "Combien de fois l'énergie solaire reçue par la Terre en une heure suffirait-elle à alimenter l'humanité ?", answer: "Pendant un an entier" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — CORPS HUMAIN (25)
  // ══════════════════════════════════════════════════════════
  { question: "À quelle vitesse un éternuement expulse-t-il l'air hors du corps ?", answer: "Jusqu'à 160 km/h" },
  { question: "Combien de fois le cœur bat-il dans une vie humaine complète de 80 ans ?", answer: "Plus de 2,5 milliards de fois" },
  { question: "Quel est le muscle le plus fort du corps humain par rapport à sa taille ?", answer: "Le masséter (la mâchoire, jusqu'à 68 kg de pression)" },
  { question: "Quelle est la surface totale des poumons si on les dépliait entièrement ?", answer: "Environ 70 m² (comme un terrain de tennis)" },
  { question: "Combien d'odeurs différentes le nez humain peut-il distinguer ?", answer: "Plus d'un trillion (10¹²) d'odeurs" },
  { question: "À quelle pression le cœur éjecte-t-il le sang à chaque battement ?", answer: "Suffisante pour projeter du sang à 9 mètres de haut" },
  { question: "Combien d'os composent le crâne humain ?", answer: "8 os" },
  { question: "Combien de types de cellules différentes contient le corps humain ?", answer: "Plus de 200 types" },
  { question: "Quelle est la pression exercée par les dents lors d'une morsure puissante ?", answer: "Jusqu'à 120 kg/cm²" },
  { question: "Combien de calories brûle-t-on en dormant 8 heures ?", answer: "Environ 500 calories" },
  { question: "Combien de muscles contient la langue humaine ?", answer: "8 muscles" },
  { question: "Combien d'années de sommeil représente une vie humaine de 80 ans ?", answer: "Environ 25 à 30 ans" },
  { question: "À quelle température le corps humain entre-t-il en hypothermie légère ?", answer: "En dessous de 35°C" },
  { question: "Combien de km de cheveux un être humain produit-il dans toute sa vie ?", answer: "Environ 950 km" },
  { question: "Combien de fois par minute cligne-t-on des yeux en lisant sur un écran ?", answer: "Seulement 4 à 5 fois (contre 15 normalement)" },
  { question: "Combien de décisions conscientes prend un humain en moyenne par jour ?", answer: "Environ 35 000" },
  { question: "Quel pourcentage de nos rêves oublie-t-on dans les 5 minutes suivant le réveil ?", answer: "Environ 90%" },
  { question: "Combien de mètres de capillaires sanguins contient le cerveau humain ?", answer: "Environ 600 km" },
  { question: "Combien de litres d'urine produit-on par jour en moyenne ?", answer: "Environ 1,5 litre" },
  { question: "Combien de secondes met-on à former une première impression visuelle d'une personne ?", answer: "Moins d'une seconde (100 à 200 millisecondes)" },
  { question: "Combien de mots par minute un lecteur très entraîné peut-il lire ?", answer: "Jusqu'à 700 mots/min" },
  { question: "Combien d'os perd-on en grandissant de la naissance à l'âge adulte ?", answer: "Entre 70 et 100 os (ils fusionnent)" },
  { question: "Quelle est la durée de l'attention humaine avant distraction, inférieure à celle d'un poisson rouge ?", answer: "Environ 8 secondes" },
  { question: "Combien de litres de larmes produit-on sur une vie entière ?", answer: "Environ 65 litres" },
  { question: "Combien de millions de globules rouges produit la moelle osseuse chaque seconde ?", answer: "Environ 2 millions par seconde" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — HISTOIRE (30)
  // ══════════════════════════════════════════════════════════
  { question: "Quelle est la guerre la plus courte de l'Histoire ?", answer: "La guerre Anglo-Zanzibar (38 à 45 minutes, 1896)" },
  { question: "Quel est le premier pays à avoir accordé le droit de vote aux femmes ?", answer: "La Nouvelle-Zélande (1893)" },
  { question: "Quel pays possède le plus vieux drapeau national encore en usage ?", answer: "Le Danemark (le Dannebrog, depuis 1370)" },
  { question: "En quelle année le dernier mammouth a-t-il vécu, contemporain des pharaons ?", answer: "Vers 1650 avant J.-C. (île Wrangel)" },
  { question: "Combien de langues parlait Cléopâtre ?", answer: "9 langues" },
  { question: "Quel est le premier pays à avoir aboli l'esclavage de manière permanente ?", answer: "Haïti (1804)" },
  { question: "En quelle année le premier vol motorisé a-t-il eu lieu, et combien de secondes a-t-il duré ?", answer: "1903, les frères Wright ont volé 12 secondes" },
  { question: "Quel empire a duré le plus longtemps de l'Histoire ?", answer: "L'empire romain d'Orient/Byzance (environ 1 058 ans)" },
  { question: "En quelle année la France a-t-elle aboli la peine de mort ?", answer: "1981" },
  { question: "Quel est le premier pays à avoir lancé un satellite artificiel dans l'espace ?", answer: "L'URSS (Spoutnik 1, 1957)" },
  { question: "Quelle est la plus ancienne monnaie encore en usage dans le monde ?", answer: "La livre sterling (depuis 775 ap. J.-C.)" },
  { question: "Quel pays a inventé le concept de quarantaine médicale ?", answer: "La République de Venise (1377, 40 jours d'isolement)" },
  { question: "En quelle année le dernier exécuté à la guillotine en France a-t-il été décapité ?", answer: "1977 (Hamida Djandoubi)" },
  { question: "Combien de soldats ont péri lors de la bataille de la Somme en 1916 ?", answer: "Environ 1 million de morts et blessés" },
  { question: "En quelle année la Chine a-t-elle construit sa première Grande Muraille ?", answer: "Vers 221 avant J.-C. (sous Qin Shi Huang)" },
  { question: "Quel pays a décriminalisé l'homosexualité en premier en Europe ?", answer: "La France (1791, pendant la Révolution)" },
  { question: "Combien d'années s'est-il passé entre l'invention du téléphone et celle d'internet ?", answer: "Environ 100 ans (1876 vs 1969 pour ARPANET)" },
  { question: "Quelle est la plus longue guerre de l'Histoire de l'Europe ?", answer: "La Reconquista espagnole (781 ans, 711-1492)" },
  { question: "Quel pays possède la plus ancienne constitution écrite toujours en vigueur ?", answer: "Les États-Unis (depuis 1788)" },
  { question: "En quelle année l'imprimerie a-t-elle été inventée en Chine, soit 400 ans avant Gutenberg ?", answer: "Vers 1040 ap. J.-C. (Bi Sheng)" },
  { question: "Combien de temps Napoléon a-t-il régné en comptant les Cent-Jours ?", answer: "Environ 6 ans (1804-1815, avec exil)" },
  { question: "Quelle est la plus grande invasion militaire terrestre de l'Histoire ?", answer: "L'opération Barbarossa (juin 1941, plus de 3 millions de soldats)" },
  { question: "En quelle année fut construit le premier chemin de fer public à vapeur ?", answer: "1825 (Angleterre, Stockton-Darlington)" },
  { question: "Quel roi d'Angleterre a régné le moins longtemps ?", answer: "Édouard V (environ 86 jours, 1483)" },
  { question: "En quelle année la Tour de Londres a-t-elle été construite ?", answer: "1078 (sous Guillaume le Conquérant)" },
  { question: "Combien d'empereurs différents Rome a-t-elle eu en une seule année (235 ap. J.-C.) ?", answer: "3 empereurs en un an (la crise du IIIe siècle)" },
  { question: "Quel pays a possédé le plus grand empire colonial par superficie ?", answer: "Le Royaume-Uni (jusqu'à 35 millions de km²)" },
  { question: "En quelle année le premier vaccin a-t-il été mis au point ?", answer: "1796 (Edward Jenner, contre la variole)" },
  { question: "Quel pays a l'histoire démocratique la plus ancienne du monde ?", answer: "L'Islande (Althing, fondé en 930 ap. J.-C.)" },
  { question: "Combien d'hommes ont marché sur la Lune jusqu'à aujourd'hui ?", answer: "12 hommes (entre 1969 et 1972)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — ALIMENTATION (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est l'aliment le plus consommé dans le monde ?", answer: "Le riz" },
  { question: "Quel pays est le plus grand consommateur de chocolat par habitant ?", answer: "La Suisse (environ 10 kg par personne par an)" },
  { question: "Dans quel pays a-t-on retrouvé le plus vieux vin connu, âgé de 8 000 ans ?", answer: "En Géorgie (Caucase)" },
  { question: "Combien de litres d'eau faut-il pour produire 1 kg de viande de bœuf ?", answer: "Environ 15 400 litres" },
  { question: "Quel est l'aliment le plus épicé du monde ?", answer: "Le piment Carolina Reaper (2,2 millions de Scoville)" },
  { question: "Combien d'années un pot de miel retrouvé dans une tombe peut-il rester consommable ?", answer: "Plus de 3 000 ans (retrouvé intact dans des pyramides)" },
  { question: "Quel fruit botanique n'est pas vraiment un fruit selon les botanistes ?", answer: "La fraise (c'est un faux-fruit, un réceptacle floral)" },
  { question: "Combien de kg de café un Finlandais boit-il par an en moyenne ?", answer: "Environ 12 kg (les plus grands consommateurs au monde)" },
  { question: "Quel est le légume le plus produit dans le monde ?", answer: "La pomme de terre" },
  { question: "Combien d'espèces de piments recense-t-on dans le monde ?", answer: "Plus de 4 000 variétés" },
  { question: "Quel pays a inventé les frites ?", answer: "La Belgique (et non la France)" },
  { question: "Combien de litres de lait faut-il pour produire 1 kg de fromage ?", answer: "Environ 10 litres" },
  { question: "Quel est le fruit avec la teneur en sucre naturel la plus élevée ?", answer: "Le kaki (environ 28% de sucre)" },
  { question: "Quel pays est le plus grand producteur de café ?", answer: "Le Brésil (environ 35% de la production mondiale)" },
  { question: "Quelle plante produit les cacahuètes sous terre ?", answer: "L'arachide (une légumineuse, pas une noix)" },
  { question: "Combien de litres de vin un Français boit-il en moyenne par an ?", answer: "Environ 45 litres" },
  { question: "Quel est le pays qui consomme le plus de sucre par habitant ?", answer: "Cuba (ou les États-Unis selon les sources)" },
  { question: "Combien de pays dans le monde produisent du café ?", answer: "Plus de 50 pays" },
  { question: "Quel est l'arôme alimentaire le plus utilisé dans le monde ?", answer: "La vanille" },
  { question: "Combien de grammes de sel un Français consomme-t-il par jour en moyenne ?", answer: "Environ 9 grammes (bien au-delà des 5g recommandés)" },
  { question: "Quel champignon est le plus cher du monde au kilo ?", answer: "La truffe blanche d'Alba (jusqu'à 8 000€ le kg)" },
  { question: "Dans quel pays est née la pizza Margherita, et en quelle année ?", answer: "En Italie (Naples) en 1889, pour la reine Margherita" },
  { question: "Combien de variétés de riz existe-t-il dans le monde ?", answer: "Plus de 40 000 variétés" },
  { question: "Quel légume contient plus de vitamine C que l'orange ?", answer: "Le poivron rouge (2 fois plus de vitamine C)" },
  { question: "Quelle épice coûte plus cher que l'or au gramme ?", answer: "Le safran (jusqu'à 30 000€ le kg)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — GÉOGRAPHIE (25)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est le seul pays entouré entièrement par un seul autre pays ?", answer: "Le Lesotho (entouré par l'Afrique du Sud)" },
  { question: "Dans combien de pays le français est-il langue officielle ?", answer: "29 pays" },
  { question: "Quelle est la plus petite mer du monde ?", answer: "La mer de Marmara (Turquie, 11 350 km²)" },
  { question: "Quel est le pays avec la densité de population la plus faible ?", answer: "La Mongolie (environ 2 habitants/km²)" },
  { question: "Combien de jours dure le trajet en train sur le Transsibérien de Moscou à Vladivostok ?", answer: "Environ 7 jours" },
  { question: "Quel est le plus long tunnel ferroviaire du monde ?", answer: "Le tunnel de base du Gothard (Suisse, 57 km)" },
  { question: "Quel est le pays qui possède le plus de millionnaires par habitant ?", answer: "Monaco" },
  { question: "Combien de pays dans le monde n'ont aucun accès à la mer ?", answer: "44 pays enclavés" },
  { question: "Quelle est l'île habitée la plus éloignée de tout continent ?", answer: "Tristan da Cunha (2 816 km de l'Afrique du Sud)" },
  { question: "Combien de pays composent l'Union européenne ?", answer: "27 pays (depuis le Brexit)" },
  { question: "Dans quel pays se trouve la plus grande plaine du monde ?", answer: "En Russie (plaine de Sibérie occidentale)" },
  { question: "Quel pays a la plus faible altitude maximale au monde ?", answer: "Les Maldives (point culminant à 2,4 mètres)" },
  { question: "Quel est le plus grand archipel du monde ?", answer: "L'Indonésie (plus de 17 000 îles)" },
  { question: "Dans quel pays se trouve le plus grand cratère de météorite au monde ?", answer: "En Afrique du Sud (Vredefort, 300 km de diamètre)" },
  { question: "Quel est le seul fleuve au monde qui coule des tropiques vers l'équateur ?", answer: "Le Congo (coule vers le nord depuis le sud)" },
  { question: "Dans quel pays se trouve la plus grande forêt boréale du monde ?", answer: "En Russie (la taïga sibérienne)" },
  { question: "Quel est le plus long pont du monde ?", answer: "Le viaduc de Danyang-Kunshan en Chine (164 km)" },
  { question: "Combien de mètres de profondeur atteint la fosse des Mariannes ?", answer: "Environ 10 935 mètres" },
  { question: "Quel pays a le plus grand nombre de frontières terrestres en km total ?", answer: "La Chine (22 117 km de frontières)" },
  { question: "Dans quelle ville se trouve le plus grand aéroport du monde par superficie ?", answer: "À Riyad (Arabie Saoudite) : l'aéroport King Fahd (776 km²)" },
  { question: "Quel est le pays avec le plus de lacs contenant plus de 10% de l'eau douce mondiale ?", answer: "Le Canada (plus de 2 millions de lacs)" },
  { question: "Quelle chaîne de montagnes sépare l'Europe de l'Asie ?", answer: "L'Oural (mais la réponse surprenante : c'est une convention, la frontière est artificielle)" },
  { question: "Quel est le pays le plus long du monde du nord au sud ?", answer: "Le Chili (4 300 km du nord au sud)" },
  { question: "Dans quel pays se trouve le lac le plus profond du monde ?", answer: "En Russie (le lac Baïkal, 1 642 m)" },
  { question: "Quel est le seul pays qui partage une frontière terrestre avec l'Inde et la Chine ?", answer: "Le Népal (et le Bhoutan)" },

  // ══════════════════════════════════════════════════════════
  // NOUVELLES QUESTIONS — INSOLITE & DIVERS (45)
  // ══════════════════════════════════════════════════════════
  { question: "Quel est le premier chien envoyé dans l'espace, et par quel pays ?", answer: "Laïka, par l'URSS (novembre 1957)" },
  { question: "Combien de langues parle-t-on en Papouasie-Nouvelle-Guinée ?", answer: "Plus de 800 langues" },
  { question: "Quel est le mot le plus long de la langue française ?", answer: "Anticonstitutionnellement (25 lettres)" },
  { question: "Quel pays compte le plus de saunas par habitant ?", answer: "La Finlande (environ 1 sauna pour 2 habitants)" },
  { question: "En quelle année le dernier duel légal en France a-t-il eu lieu ?", answer: "En 1967 (entre deux hommes politiques)" },
  { question: "Combien de cubes Rubik's sont vendus chaque année dans le monde ?", answer: "Plus de 350 millions" },
  { question: "Quel pays a le plus grand nombre de Prix Nobel par habitant ?", answer: "La Suisse (ou la Suède selon le calcul)" },
  { question: "En quelle année les toilettes avec chasse d'eau ont-elles été inventées ?", answer: "1596 (par John Harington, en Angleterre)" },
  { question: "Combien de km/h peut atteindre un volant de badminton lors d'un smash record ?", answer: "Jusqu'à 493 km/h" },
  { question: "Quel est le sport avec le plus de licenciés dans le monde ?", answer: "Le football (environ 265 millions de licenciés)" },
  { question: "Combien de cordes possède un piano de concert à queue ?", answer: "Environ 230 cordes" },
  { question: "En quelle année le premier ordinateur grand public a-t-il été vendu ?", answer: "1977 (l'Apple II)" },
  { question: "Combien de transistors contient un processeur moderne comme l'Apple M1 ?", answer: "Environ 16 milliards" },
  { question: "Quelle est la durée de vie d'un billet de 5 euros en circulation ?", answer: "Environ 1 à 2 ans" },
  { question: "Combien de données l'humanité produit-elle chaque jour ?", answer: "Environ 2,5 quintillions d'octets" },
  { question: "Combien de langues parle un polyglotte sur les 7 100 existantes en moyenne ?", answer: "La définition est floue, mais on considère qu'il en parle plus de 6" },
  { question: "Quel est le monument le plus photographié au monde ?", answer: "L'Empire State Building (New York)" },
  { question: "Combien de fois par seconde un processeur moderne effectue-t-il des opérations ?", answer: "Des milliards de fois par seconde (GHz)" },
  { question: "Quel pays compte le plus de kilomètres d'autoroutes au monde ?", answer: "Les États-Unis (plus de 77 000 km)" },
  { question: "Combien d'années a duré la construction de la cathédrale de Cologne ?", answer: "Plus de 600 ans (1248-1880)" },
  { question: "Quel est le pays avec le plus grand nombre de musées au monde ?", answer: "Les États-Unis (environ 35 000 musées)" },
  { question: "Combien pèse la cloche la plus lourde du monde, à Moscou ?", answer: "Environ 202 tonnes (le Tsar Kolokol)" },
  { question: "Quel est le pays qui dépense le plus en armement par habitant ?", answer: "Israël (ou les États-Unis selon le critère)" },
  { question: "En quelle année la montre a-t-elle été inventée ?", answer: "Vers 1510 (par Peter Henlein, en Allemagne)" },
  { question: "Combien de km de routes existent dans le monde entier ?", answer: "Plus de 64 millions de km" },
  { question: "Quel est le seul pays où la langue officielle est le luxembourgeois ?", answer: "Le Luxembourg" },
  { question: "Combien d'œuvres d'art contient le musée du Louvre ?", answer: "Environ 380 000 œuvres (35 000 exposées)" },
  { question: "En quelle année la photographie couleur a-t-elle été inventée ?", answer: "1861 (par James Clerk Maxwell)" },
  { question: "Quel est le premier pays à avoir utilisé les billets de banque ?", answer: "La Chine (sous la dynastie Tang, vers 618 ap. J.-C.)" },
  { question: "Combien de fois par an le Mont-Blanc perd-il ou gagne-t-il de l'altitude selon les mesures ?", answer: "Plusieurs mètres selon les saisons (neige/glace)" },
  { question: "Quel est le premier jeu vidéo commercialement vendu dans l'Histoire ?", answer: "Pong (Atari, 1972)" },
  { question: "Combien de km de câbles sous-marins transportent 99% des communications internet mondiales ?", answer: "Plus de 1,3 million de km" },
  { question: "En quelle année le téléphone portable a-t-il été inventé ?", answer: "1973 (Martin Cooper, Motorola, premier appel mobile)" },
  { question: "Quel pays est le plus grand producteur d'énergie solaire au monde ?", answer: "La Chine" },
  { question: "Combien de personnes ont été dans l'espace depuis 1961 ?", answer: "Plus de 600 personnes" },
  { question: "Quel est le pays avec le plus de frontières maritimes dans le monde ?", answer: "L'Indonésie" },
  { question: "En quelle année les lunettes ont-elles été inventées ?", answer: "Vers 1286 (en Italie, à Pise)" },
  { question: "Combien de mètres de hauteur perd la Tour Eiffel en hiver par rapport à l'été ?", answer: "Jusqu'à 15 cm (la structure métallique se contracte)" },
  { question: "Quel pays a le plus grand réseau ferroviaire du monde ?", answer: "Les États-Unis (environ 250 000 km de voies)" },
  { question: "Combien de langues officielles l'ONU reconnaît-elle ?", answer: "6 langues officielles" },
  { question: "Quel est le seul sport où les femmes et les hommes s'affrontent en compétition officielle ?", answer: "L'équitation (aux Jeux Olympiques)" },
  { question: "En quelle année internet a-t-il dépassé 1 milliard d'utilisateurs ?", answer: "En 2005 (environ)" },
  { question: "Combien de satellites artificiels orbitent autour de la Terre actuellement ?", answer: "Plus de 7 000 satellites actifs" },
  { question: "Quel pays a inventé le karaoké ?", answer: "Le Japon (1971, par Daisuke Inoue)" },
  { question: "Combien de pays ont leur propre programme nucléaire civil actif ?", answer: "Environ 30 pays" },

];

module.exports = { questions };
